-- Update 4.9: Configure Trusted DNS Servers on Enterprise Assets...\nUPDATE requirements_library SET\n  title = 'Configure Trusted DNS Servers on Enterprise Assets',\n  description = 'Configure trusted DNS servers on enterprise assets. Example implementations include: configuring assets to use enterprise-controlled DNS servers and/or reputable externally accessible DNS servers.',\n  updated_at = NOW()\nWHERE id = '6815fb76-77d7-4963-a157-e5c0bf5ae8dd';

-- Update 6.7: Centralize Access Control...\nUPDATE requirements_library SET\n  title = 'Centralize Access Control',\n  description = 'Centralize access control for all enterprise assets through a directory service or SSO provider, where supported.',\n  updated_at = NOW()\nWHERE id = '88308310-4784-447b-a83f-9b1decea337a';

-- Update 17.8: Conduct Post-Incident Reviews...\nUPDATE requirements_library SET\n  title = 'Conduct Post-Incident Reviews',\n  description = 'Conduct post-incident reviews. Post-incident reviews help prevent recurrence of incidents, as well as improve security practices.',\n  updated_at = NOW()\nWHERE id = 'eacbc2cb-92db-45f9-bdf1-bdea6254b728';

-- Update 5.5: Establish and Maintain an Inventory of Service Accounts...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain an Inventory of Service Accounts',\n  description = 'Establish and maintain an inventory of service accounts. The inventory shall include, but is not limited to, purpose, ownership, and authorized users of the account. Perform service account reviews to validate that all service accounts are authorized, warranted, and privileged are still required, on a recurring schedule at a minimum annually, or more frequently.',\n  updated_at = NOW()\nWHERE id = '202d94b0-2d70-4bea-8a5e-ee0fddc1c3b3';

-- Update 5.6: Centralize Account Management...\nUPDATE requirements_library SET\n  title = 'Centralize Account Management',\n  description = 'Centralize account management through a directory service.',\n  updated_at = NOW()\nWHERE id = '1bee12bd-1ccd-40f8-9c29-dee9ce4f6881';

-- Update 16.6: Establish and Maintain a Severity Rating System and Process ...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Severity Rating System and Process for Application Vulnerabilities',\n  description = 'Establish and maintain a severity rating system and process for application vulnerabilities that facilitates prioritizing the order in which discovered vulnerabilities are fixed. This process includes setting a minimum level of security acceptability for releasing code or applications.',\n  updated_at = NOW()\nWHERE id = 'd1cb5f11-21b8-48a1-863d-6e9151eef6ad';

-- Update 16.7: Use Standard Hardening Configuration Templates for Applicati...\nUPDATE requirements_library SET\n  title = 'Use Standard Hardening Configuration Templates for Application Infrastructure',\n  description = 'Use standard, industry-recommended hardening configuration templates for application infrastructure components. This includes underlying servers, databases, and web servers, and applies to cloud containers, Platform as a Service (PaaS) components, or Software as a Service (SaaS) components used as application infrastructure.',\n  updated_at = NOW()\nWHERE id = 'db8dcf98-a0d7-48fa-bbb7-5655169832ca';

-- Update 4.4: Implement and Manage a Firewall on Servers...\nUPDATE requirements_library SET\n  title = 'Implement and Manage a Firewall on Servers',\n  description = 'Implement and manage a firewall on servers, where supported. Example implementations include a virtual firewall, operating system firewall, or a physical firewall.',\n  updated_at = NOW()\nWHERE id = '11fccd63-0b04-41d3-b9ba-2570b98d97bc';