-- Update 5.2: Use Unique Passwords...\nUPDATE requirements_library SET\n  title = 'Use Unique Passwords',\n  description = 'Use unique passwords for all enterprise assets. Best practice implementation includes, at a minimum, an 8-character password for accounts using MFA and a 14-character password for accounts not using MFA.',\n  updated_at = NOW()\nWHERE id = '9728659d-8a86-46c9-a96d-fc8bb6b3800d';

-- Update 7.2: Establish and Maintain a Remediation Process...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Remediation Process',\n  description = 'Establish and maintain a documented remediation process for enterprise assets with a vulnerability management process.',\n  updated_at = NOW()\nWHERE id = '33464558-6f0f-4a02-9e44-9320da356bc1';

-- Update 3.2: Establish and Maintain a Data Inventory...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Data Inventory',\n  description = 'Establish and maintain a documented data inventory based on the enterprise''s data management process. Inventory data with a sensitivity of high or very high, or data subject to regulatory requirements. The inventory shall include location, volume, sensitivity, owner, custodian, cloud service provider used, and determine if the location is a new location for the enterprise.',\n  updated_at = NOW()\nWHERE id = '4cfa8579-abe0-4d7e-8241-db1a36bae6e9';

-- Update 8.1: Establish and Maintain an Audit Log Management Process...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain an Audit Log Management Process',\n  description = 'Establish and maintain an audit log management process that defines the enterprise''s logging requirements. At a minimum, address the collection, review, and retention of audit logs for enterprise assets. Review and update documentation annually, or when significant enterprise changes occur that could impact this Safeguard.',\n  updated_at = NOW()\nWHERE id = '48a16fe2-a266-4f57-88f9-cc20cd7e6542';

-- Update 14.3: Train Workforce Members on Authentication Best Practices...\nUPDATE requirements_library SET\n  title = 'Train Workforce Members on Authentication Best Practices',\n  description = 'Train workforce members on authentication best practices. Example topics include creating secure passwords, password managers, MFA, and phishing-resistant MFA.',\n  updated_at = NOW()\nWHERE id = 'd5ddf11d-45a6-448b-a7a3-352bb11dc22b';

-- Update 14.4: Train Workforce on Data Handling Best Practices...\nUPDATE requirements_library SET\n  title = 'Train Workforce on Data Handling Best Practices',\n  description = 'Train workforce members on data handling best practices. Example topics include appropriate use, handling requirements, acceptable locations for storage, encryption, and destruction.',\n  updated_at = NOW()\nWHERE id = 'f995d497-30f7-4a0b-b263-5c94b484a7c8';

-- Update 9.1: Ensure Use of Only Fully Supported Browsers and Email Client...\nUPDATE requirements_library SET\n  title = 'Ensure Use of Only Fully Supported Browsers and Email Clients',\n  description = 'Ensure only fully supported browsers and email clients are allowed to execute in the enterprise, only using the latest version of browsers and email clients provided by the vendor.',\n  updated_at = NOW()\nWHERE id = 'fcabf985-a8e7-47e4-b6a2-4aac2b5152ee';

-- Update 14.5: Train Workforce Members on Causes of Unintentional Data Expo...\nUPDATE requirements_library SET\n  title = 'Train Workforce Members on Causes of Unintentional Data Exposure',\n  description = 'Train workforce members to be aware of causes for unintentional data exposure. Example topics include mis-delivery of sensitive data, losing a portable end-user device, or publishing data to unintended audiences.',\n  updated_at = NOW()\nWHERE id = '53041334-f29c-4d18-9567-495ec4dc1118';