-- Update 1.1: Establish and Maintain Detailed Enterprise Asset Inventory...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain Detailed Enterprise Asset Inventory',\n  description = 'Establish and maintain an accurate, detailed, and up-to-date inventory of all enterprise assets with the potential to store or process data, to include: end-user devices (including portable and mobile), network devices, non-computing/IoT devices, and servers. Ensure the inventory records the network address (if static), hardware address, machine name, enterprise asset owner, department for each asset, and whether the asset has been approved to connect to the network. For mobile end-user devices, MDM type tools can support this process, where appropriate. This inventory includes assets connected to the infrastructure physically, virtually, remotely, and those within cloud environments. Additionally, it includes assets that are regularly connected to the enterprise''s network infrastructure, even if they are not under control of the enterprise. Review and update the inventory of all enterprise assets bi-annually, or more frequently.',\n  updated_at = NOW()\nWHERE id = '4ea21cbb-9cd4-4c1f-91a7-ee12a3f4f671';

-- Update 1.4: Use Dynamic Host Configuration Protocol (DHCP) Logging to Up...\nUPDATE requirements_library SET\n  title = 'Use Dynamic Host Configuration Protocol (DHCP) Logging to Update Enterprise Asset Inventory',\n  description = 'Use DHCP logging on all DHCP servers or Internet Protocol (IP) address management tools to update the enterprise''s asset inventory. Review and use logs to update the enterprise''s asset inventory weekly, or more frequently.',\n  updated_at = NOW()\nWHERE id = '2d51f01b-cb3a-472b-bffc-dd4e52aa9d1c';

-- Update 4.1: Establish and Maintain a Secure Configuration Process...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Secure Configuration Process',\n  description = 'Establish and maintain a documented secure configuration process for enterprise assets (end-user devices, including portable and mobile, non-computing/IoT devices, and servers) and software (operating systems and applications). Review and update documentation annually, or when significant enterprise changes occur that could impact this Safeguard.',\n  updated_at = NOW()\nWHERE id = 'fab46f62-aa57-4781-85a4-21665545ce00';

-- Update 6.1: Establish an Access Granting Process...\nUPDATE requirements_library SET\n  title = 'Establish an Access Granting Process',\n  description = 'Establish and follow a process for granting access to enterprise assets upon new hire, promotion, or role change of a user.',\n  updated_at = NOW()\nWHERE id = '7101a8dc-3768-4032-81a6-be217090e63a';

-- Update 6.2: Establish an Access Revoking Process...\nUPDATE requirements_library SET\n  title = 'Establish an Access Revoking Process',\n  description = 'Establish and follow a process for revoking access to enterprise assets, through disabling accounts immediately upon termination, rights revocation, or role change of a user. Disabling accounts, instead of deleting accounts, allows preservation of audit trails.',\n  updated_at = NOW()\nWHERE id = '537cf193-d726-4d8f-b561-15866ccd2fc8';

-- Update 6.4: Require MFA for Remote Network Access...\nUPDATE requirements_library SET\n  title = 'Require MFA for Remote Network Access',\n  description = 'Require all users to use multi-factor authentication (MFA) for remote network access.',\n  updated_at = NOW()\nWHERE id = 'c7d5eb8b-d7d6-48f7-bac8-f20a595d5843';

-- Update 6.3: Require MFA for Externally-Exposed Applications...\nUPDATE requirements_library SET\n  title = 'Require MFA for Externally-Exposed Applications',\n  description = 'Require all users to use multi-factor authentication (MFA) for externally-exposed enterprise or third-party applications.',\n  updated_at = NOW()\nWHERE id = 'cfd6d9dc-225f-4dde-ba53-551c13146481';

-- Update 7.3: Perform Automated Operating System Patch Management...\nUPDATE requirements_library SET\n  title = 'Perform Automated Operating System Patch Management',\n  description = 'Perform operating system updates on enterprise assets through automated patch management on a monthly, or more frequent, basis.',\n  updated_at = NOW()\nWHERE id = '56a0568d-16c3-4dfd-8e80-465a50df65ab';