-- Updates ONLY titles and descriptions from backup\n-- Preserves all other columns and recent changes\n\n-- ISO27001 Requirements (24 total)\n\n-- Update 4.1: Establish and Maintain a Secure Configuration Process...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Secure Configuration Process',\n  description = 'Establish and maintain a documented secure configuration process for enterprise assets (end-user devices, including portable and mobile, non-computing/IoT devices, and servers) and software (operating systems and applications). Review and update documentation annually, or when significant enterprise changes occur that could impact this Safeguard.',\n  updated_at = NOW()\nWHERE id = 'ab8fd5d0-479b-4b05-9f4a-727b68b08ef1';

-- Update 4.2: Establish and Maintain a Secure Configuration Process for Ne...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Secure Configuration Process for Network Infrastructure',\n  description = 'Establish and maintain a documented secure configuration process for network infrastructure. Review and update documentation annually, or when significant enterprise changes occur that could impact this Safeguard.',\n  updated_at = NOW()\nWHERE id = '6af9aeee-62ff-49ba-bf79-e19c7c814bc3';

-- Update 4.3: Configure Automatic Session Locking on Enterprise Assets...\nUPDATE requirements_library SET\n  title = 'Configure Automatic Session Locking on Enterprise Assets',\n  description = 'Configure automatic session locking on enterprise assets after a defined period of inactivity. For general purpose operating systems, the period must not exceed 15 minutes. For mobile end-user devices, the period must not exceed 2 minutes.',\n  updated_at = NOW()\nWHERE id = '3ddc0fc5-19c3-4353-9de7-84394b8ce827';

-- Update 7.4: Perform Automated Application Patch Management...\nUPDATE requirements_library SET\n  title = 'Perform Automated Application Patch Management',\n  description = 'Perform application updates on enterprise assets through automated patch management on a monthly, or more frequent, basis.',\n  updated_at = NOW()\nWHERE id = 'dc81b8ae-9d36-4a2c-99e9-a81e5b0627de';

-- Update 6.1.1: General actions to address risks and opportunities...\nUPDATE requirements_library SET\n  title = 'General actions to address risks and opportunities',\n  description = 'When planning for the information security management system, the organization shall consider the issues referred to in 4.1 and the requirements referred to in 4.2 and determine the risks and opportunities that need to be addressed. Implementation: Identify all risks and opportunities related to information security. Consider internal and external context factors. Address stakeholder requirements and expectations. Document risk and opportunity assessment process.',\n  updated_at = NOW()\nWHERE id = 'da21e2f2-56ab-4db2-9f61-fc27ee9dd08b';

-- Update 6.1.2: Information security risk assessment...\nUPDATE requirements_library SET\n  title = 'Information security risk assessment',\n  description = 'The organization shall define and apply an information security risk assessment process that establishes and maintains information security risk criteria and consistently produces comparable and reproducible results. Implementation: Establish formal risk assessment methodology. Define risk acceptance criteria and risk evaluation criteria. Ensure consistent application across all assessments. Document risk assessment process and results.',\n  updated_at = NOW()\nWHERE id = 'a7a199a0-fa42-4f02-ae0e-c87f5bbcefa0';

-- Update 6.1.3: Information security risk treatment...\nUPDATE requirements_library SET\n  title = 'Information security risk treatment',\n  description = 'The organization shall define and apply an information security risk treatment process to select appropriate information security risk treatment options and determine all controls that are necessary to implement the information security risk treatment option(s) chosen. Implementation: Define risk treatment options (accept, avoid, transfer, mitigate). Select appropriate controls for risk treatment. Document risk treatment decisions and rationale. Implement selected controls systematically.',\n  updated_at = NOW()\nWHERE id = 'f7d97f0e-4ca0-4ddb-b4a6-28b2b7b79859';

-- Update 5.1: Establish and Maintain an Inventory of Accounts...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain an Inventory of Accounts',\n  description = 'Establish and maintain an inventory of all accounts managed in the enterprise. The inventory shall include both user and administrator accounts. The inventory shall include the person or entity the account belongs to, the systems it applies to, and an active or inactive status. Review the inventory quarterly, or more frequently.',\n  updated_at = NOW()\nWHERE id = '4ab658ff-729b-4a3e-88aa-5aa3b2a8caa6';