-- Update 8.12: Collect Service Provider Logs...\nUPDATE requirements_library SET\n  title = 'Collect Service Provider Logs',\n  description = 'Collect service provider logs. Example implementations include collecting authentication and authorization events, data creation and disposal events, and user management events.',\n  updated_at = NOW()\nWHERE id = '63ffc696-bc3d-4960-bca7-7355a93db643';

-- Update 14.3: Train Workforce Members on Authentication Best Practices...\nUPDATE requirements_library SET\n  title = 'Train Workforce Members on Authentication Best Practices',\n  description = 'Train workforce members on authentication best practices. Example topics include creating secure passwords, password managers, MFA, and phishing-resistant MFA.',\n  updated_at = NOW()\nWHERE id = 'e5a79db8-0617-4647-9c40-34e0659c2b06';

-- Update 9.3: Maintain and Enforce Network-Based URL Filters...\nUPDATE requirements_library SET\n  title = 'Maintain and Enforce Network-Based URL Filters',\n  description = 'Enforce and update network-based URL filters to limit an enterprise asset from connecting to potentially malicious or inappropriate websites. Example implementations include category-based filtering, reputation-based filtering, or through the use of block lists. Web filtering shall be enforced on all enterprise assets.',\n  updated_at = NOW()\nWHERE id = '4c47a209-8911-4b9a-ac6d-e32e9ecd66d9';

-- Update 7.1: Establish and Maintain a Vulnerability Management Process...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Vulnerability Management Process',\n  description = 'Establish and maintain a documented vulnerability management process for enterprise assets. Review and update documentation annually, or when significant enterprise changes occur that could impact this Safeguard.',\n  updated_at = NOW()\nWHERE id = '131a8253-a4e2-48b5-b713-d4f45d3ff009';

-- Update 14.4: Train Workforce on Data Handling Best Practices...\nUPDATE requirements_library SET\n  title = 'Train Workforce on Data Handling Best Practices',\n  description = 'Train workforce members on data handling best practices. Example topics include appropriate use, handling requirements, acceptable locations for storage, encryption, and destruction.',\n  updated_at = NOW()\nWHERE id = '9ec8f760-97c7-4017-bd92-3ae304b341b6';

-- Update 13.5: Manage Access Control for Remote Assets...\nUPDATE requirements_library SET\n  title = 'Manage Access Control for Remote Assets',\n  description = 'Manage access control for assets remotely connecting to enterprise resources. Determine amount of access to enterprise resources based on: up-to-date anti-malware software installed, patch level of the operating system and applications, integrity of those applications, and proper configuration.',\n  updated_at = NOW()\nWHERE id = '044d2718-1138-44e0-b4bf-bcf67adfd59e';

-- Update 14.5: Train Workforce Members on Causes of Unintentional Data Expo...\nUPDATE requirements_library SET\n  title = 'Train Workforce Members on Causes of Unintentional Data Exposure',\n  description = 'Train workforce members on causes of unintentional data exposure. Implementation: Educate users on common causes of data exposure and leakage. Provide training on data loss prevention practices. Train on secure communication and sharing practices. Conduct regular awareness updates on emerging threats.',\n  updated_at = NOW()\nWHERE id = 'b0d6e470-f049-42f9-825b-e6f15e696138';

-- Update 14.7: Train Workforce on How to Identify and Report if Their Enter...\nUPDATE requirements_library SET\n  title = 'Train Workforce on How to Identify and Report if Their Enterprise Assets are Missing Security Updates',\n  description = 'Train workforce on how to identify and report if their enterprise assets are missing security updates. Implementation: Educate users on security update importance and identification. Provide training on update status checking procedures. Train on reporting mechanisms for missing updates. Establish update compliance monitoring and reporting.',\n  updated_at = NOW()\nWHERE id = '10775d5a-bca1-4406-a76c-4ced5b51491b';