-- Update 3.1: Establish and Maintain a Data Management Process...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Data Management Process',\n  description = 'Establish and maintain a documented data management process. In the process, address data sensitivity, data owner, handling of data, data retention limits, and disposal requirements, based on sensitivity and retention standards for the enterprise. Review and update documentation annually, or when significant enterprise changes occur that could impact this Safeguard.',\n  updated_at = NOW()\nWHERE id = 'b071ac99-0cb6-4d51-9464-9532d3cf3e9d';

-- Update 18.2: Perform Periodic External Penetration Tests...\nUPDATE requirements_library SET\n  title = 'Perform Periodic External Penetration Tests',\n  description = 'Perform periodic external penetration tests based on program requirements, no less than annually. External penetration testing must include enterprise and environmental reconnaissance to gather information that an attacker would use. Also, testing must include threat identification and, at a minimum, network, web application, and social engineering testing.',\n  updated_at = NOW()\nWHERE id = 'eeec6ba3-612b-496c-874a-f36229a93b60';

-- Update 8.7: Collect URL Request Audit Logs...\nUPDATE requirements_library SET\n  title = 'Collect URL Request Audit Logs',\n  description = 'Collect Uniform Resource Locator (URL) request logging. Logging systems need to be configured to collect URL requests from each of the enterprise''s web-facing applications.',\n  updated_at = NOW()\nWHERE id = '72e3a75b-fff7-4cef-96f8-bb3838f74ccf';

-- Update 8.8: Collect Command-Line Audit Logs...\nUPDATE requirements_library SET\n  title = 'Collect Command-Line Audit Logs',\n  description = 'Collect command-line audit logs. Example implementations include collecting audit logs from PowerShell®, BASH history, or Windows Command Prompt.',\n  updated_at = NOW()\nWHERE id = '3450ff03-cf18-44b4-9881-5b2551345a99';

-- Update 8.6: Collect DNS Query Audit Logs...\nUPDATE requirements_library SET\n  title = 'Collect DNS Query Audit Logs',\n  description = 'Enable Domain Name System (DNS) query logging to collect DNS queries sent by enterprise assets.',\n  updated_at = NOW()\nWHERE id = '911d2fa0-97d6-4559-a961-e6150a0ac30f';

-- Update 3.11: Encrypt Sensitive Data at Rest...\nUPDATE requirements_library SET\n  title = 'Encrypt Sensitive Data at Rest',\n  description = 'Encrypt sensitive data at rest on servers, applications, and databases containing sensitive data. Storage-layer encryption, also known as server-side encryption, meets the intent of this Safeguard. Additional encryption methods may include application-layer encryption, also known as client-side encryption, where access to the data storage device(s) does not permit access to the plain-text data.',\n  updated_at = NOW()\nWHERE id = '20e76f7d-8bcb-41b8-9334-bfd47575d568';

-- Update 3.3: Configure Data Access Control Lists...\nUPDATE requirements_library SET\n  title = 'Configure Data Access Control Lists',\n  description = 'Configure data access control lists based on a user''s need to know. Apply data access control lists, also known as access permissions, to local and remote file systems, databases, and applications.',\n  updated_at = NOW()\nWHERE id = '8dd9a00f-aa64-4fc5-a828-41f5bbcfcf52';

-- Update 3.4: Enforce Data Retention...\nUPDATE requirements_library SET\n  title = 'Enforce Data Retention',\n  description = 'Retain data according to the enterprise''s data management process. Data retention must include both minimum and maximum timelines.',\n  updated_at = NOW()\nWHERE id = '8c0ed353-59c9-46f9-873d-2e034abee883';