-- Update 5.21: Managing information security in the ICT supply chain...\nUPDATE requirements_library SET\n  title = 'Managing information security in the ICT supply chain',\n  description = 'Processes and procedures shall be defined and implemented to manage the information security risks associated with the products and services in the ICT supply chain.',\n  updated_at = NOW()\nWHERE id = '0ed199f2-56a7-4d3f-9269-37a204c57b7a';

-- Update 5.22: Monitoring, review and change management of supplier service...\nUPDATE requirements_library SET\n  title = 'Monitoring, review and change management of supplier services',\n  description = 'The organization shall regularly monitor, review, evaluate and manage change in supplier information security practices and service delivery.',\n  updated_at = NOW()\nWHERE id = 'fc963a7c-3db1-4753-addf-18e6a91bc116';

-- Update 5.23: Information security for use of cloud services...\nUPDATE requirements_library SET\n  title = 'Information security for use of cloud services',\n  description = 'Processes for acquisition, use, management and exit from cloud services shall be established in accordance with the organization''s information security requirements.',\n  updated_at = NOW()\nWHERE id = '6af15069-d126-44bd-aee9-6513b7b56f88';

-- Update 5.24: Information security incident management planning and prepar...\nUPDATE requirements_library SET\n  title = 'Information security incident management planning and preparation',\n  description = 'The organization shall plan and prepare for managing information security incidents by defining, establishing and communicating information security incident management processes, roles and responsibilities.',\n  updated_at = NOW()\nWHERE id = 'bb7d6877-fac8-4db8-b34b-cc28542eaa33';

-- Update 5.25: Assessment and decision on information security events...\nUPDATE requirements_library SET\n  title = 'Assessment and decision on information security events',\n  description = 'The organization shall assess information security events and decide if they are to be categorized as information security incidents.',\n  updated_at = NOW()\nWHERE id = 'e72a8d3e-f5a8-4bfa-ac83-0275f443ba98';

-- Update 5.26: Response to information security incidents...\nUPDATE requirements_library SET\n  title = 'Response to information security incidents',\n  description = 'Information security incidents shall be responded to in accordance with the documented procedures.',\n  updated_at = NOW()\nWHERE id = '9cc20627-9cb1-49f7-abc9-c90fb5b15266';

-- Update 5.27: Learning from information security incidents...\nUPDATE requirements_library SET\n  title = 'Learning from information security incidents',\n  description = 'Knowledge gained from analyzing and resolving information security incidents shall be used to strengthen and improve the information security controls.',\n  updated_at = NOW()\nWHERE id = '210aa83a-9af7-4d8b-aa07-3d9ac80d1f43';

-- Update 5.28: Collection of evidence...\nUPDATE requirements_library SET\n  title = 'Collection of evidence',\n  description = 'The organization shall establish and implement procedures for the identification, collection, acquisition and preservation of evidence related to information security events.',\n  updated_at = NOW()\nWHERE id = 'd0fbb9e1-ae66-43ba-b38b-c523437c4f81';