-- Update 14.1: Establish and Maintain a Security Awareness Program...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Security Awareness Program',\n  description = 'Establish and maintain a security awareness program. The purpose of a security awareness program is to educate the enterprise''s workforce on how to interact with enterprise assets and data in a secure manner. Review and update documentation annually, or when significant enterprise changes occur that could impact this Safeguard.',\n  updated_at = NOW()\nWHERE id = '7d26501b-7f54-48d7-adcf-42d687203744';

-- Update 12.1: Ensure Network Infrastructure is Up-to-Date...\nUPDATE requirements_library SET\n  title = 'Ensure Network Infrastructure is Up-to-Date',\n  description = 'Ensure network infrastructure is kept up-to-date. Example implementations include running the latest stable release of software and/or using currently supported network-infrastructure devices.',\n  updated_at = NOW()\nWHERE id = 'bfa47ede-a263-4b3e-8dd8-54efc48688dc';

-- Update 12.2: Establish and Maintain a Secure Network Architecture...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Secure Network Architecture',\n  description = 'Establish and maintain a secure network architecture. A secure network architecture must address segmentation, least privilege, and availability, at a minimum.',\n  updated_at = NOW()\nWHERE id = '9f691871-3010-4399-b45d-dfc940981de2';

-- Update 4.8: Uninstall or Disable Unnecessary Services on Enterprise Asse...\nUPDATE requirements_library SET\n  title = 'Uninstall or Disable Unnecessary Services on Enterprise Assets and Software',\n  description = 'Uninstall or disable unnecessary services on enterprise assets and software, such as an unused file sharing service, web application module, or service function.',\n  updated_at = NOW()\nWHERE id = 'fcc7ece1-4072-4b7f-b472-454bac107caf';

-- Update 9.6: Block Unnecessary File Types...\nUPDATE requirements_library SET\n  title = 'Block Unnecessary File Types',\n  description = 'Block unnecessary file types attempting to enter the enterprise''s email gateway.',\n  updated_at = NOW()\nWHERE id = '664f061c-62b7-403c-9354-b1c6b6ea2e6e';

-- Update 1.4: Use Dynamic Host Configuration Protocol (DHCP) Logging to Up...\nUPDATE requirements_library SET\n  title = 'Use Dynamic Host Configuration Protocol (DHCP) Logging to Update Enterprise Asset Inventory',\n  description = 'Use DHCP logging on all DHCP servers or Internet Protocol (IP) address management tools to update the enterprise''s asset inventory. Review and use logs to update the enterprise''s asset inventory weekly, or more frequently.',\n  updated_at = NOW()\nWHERE id = '35672fb8-1564-4370-9986-8d6eef82acc2';

-- Update 14.5: Train Workforce Members on Causes of Unintentional Data Expo...\nUPDATE requirements_library SET\n  title = 'Train Workforce Members on Causes of Unintentional Data Exposure',\n  description = 'Train workforce members to be aware of causes for unintentional data exposure. Example topics include mis-delivery of sensitive data, losing a portable end-user device, or publishing data to unintended audiences.',\n  updated_at = NOW()\nWHERE id = '0289c083-7f76-48cb-9a76-e37ad1cd74bd';

-- Update 14.7: Train Workforce on How to Identify and Report if Their Enter...\nUPDATE requirements_library SET\n  title = 'Train Workforce on How to Identify and Report if Their Enterprise Assets are Missing Security Updates',\n  description = 'Train workforce to understand how to verify and report out-of-date software patches or any failures in automated processes and tools. Part of this training should include notifying IT personnel of any failures in automated processes and tools.',\n  updated_at = NOW()\nWHERE id = 'ce0d720b-7d43-4ef9-8caa-d5772aa43184';