-- Update 9.4: Restrict Unnecessary or Unauthorized Browser and Email Clien...\nUPDATE requirements_library SET\n  title = 'Restrict Unnecessary or Unauthorized Browser and Email Client Extensions',\n  description = 'Restrict unnecessary or unauthorized browser and email client extensions, including add-ons, and plug-ins.',\n  updated_at = NOW()\nWHERE id = 'e06ed0f7-9951-4175-85d2-4055f6e3fb0c';

-- Update 11.5: Test Data Recovery...\nUPDATE requirements_library SET\n  title = 'Test Data Recovery',\n  description = 'Test backup and recovery of enterprise data on an annual basis. Testing shall include restoration of backup data to a separate system, and a test of the time required to restore from backup. Document and review test results.',\n  updated_at = NOW()\nWHERE id = '9068010a-bcc6-4b3f-986e-55dec1cb25aa';

-- Update 17.7: Conduct Routine Incident Response Exercises...\nUPDATE requirements_library SET\n  title = 'Conduct Routine Incident Response Exercises',\n  description = 'Plan and conduct routine incident response exercises and scenarios for key personnel, including elements of communication, coordination, decision making, and workflow.',\n  updated_at = NOW()\nWHERE id = '4b0772bd-904f-4efb-b5ad-27e23ac93aec';

-- Update 17.1: Establish and Maintain an Incident Response Process...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain an Incident Response Process',\n  description = 'Designate one key person, and at least one backup, who will manage the enterprise''s incident handling process. Management personnel are responsible for the coordination and documentation of incident response and recovery efforts and can consist of employees of the enterprise, third-party vendors, or a hybrid approach. If using a third-party vendor, designate at least one person internal to the enterprise to oversee any third-party work. Review annually, or when significant enterprise changes occur that could impact this Safeguard.',\n  updated_at = NOW()\nWHERE id = 'aeb9901e-248a-4afc-ad62-88596dcf7337';

-- Update 10.3: Disable Autorun and Autoplay for Removable Media...\nUPDATE requirements_library SET\n  title = 'Disable Autorun and Autoplay for Removable Media',\n  description = 'Disable autorun and autoplay auto-execute functionality for removable media.',\n  updated_at = NOW()\nWHERE id = '06c1a1f1-8405-4a94-b7c9-e290105ba2d0';

-- Update 10.4: Configure Automatic Anti-Malware Scanning of Removable Media...\nUPDATE requirements_library SET\n  title = 'Configure Automatic Anti-Malware Scanning of Removable Media',\n  description = 'Configure anti-malware software to automatically scan removable media.',\n  updated_at = NOW()\nWHERE id = '077b27a3-2682-4701-be10-e982638a929f';

-- Update 17.2: Establish and Maintain Contact Information for Reporting Sec...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain Contact Information for Reporting Security Incidents',\n  description = 'Establish and maintain contact information for parties that need to be informed of security incidents. Contacts may include internal staff, third-party vendors, law enforcement, cyber insurance providers, relevant government agencies, Information Sharing and Analysis Center (ISAC) partners, or Information Sharing and Analysis Organization (ISAO) partners. Verify contacts annually to ensure that information is up-to-date.',\n  updated_at = NOW()\nWHERE id = '8ba97737-6510-4cd1-8824-d5e4de9805a1';

-- Update 2.6: Allowlist Authorized Libraries...\nUPDATE requirements_library SET\n  title = 'Allowlist Authorized Libraries',\n  description = 'Use technical controls to ensure that only authorized software libraries, such as specific .dll, .ocx, and .so files, are allowed to load into a system process. Block unauthorized libraries from loading into a system process. Reassess bi-annually, or more frequently.',\n  updated_at = NOW()\nWHERE id = '6dae5c6d-c2b4-4343-a35a-f75d452abac6';