-- Update 14.7: Train Workforce on How to Identify and Report if Their Enter...\nUPDATE requirements_library SET\n  title = 'Train Workforce on How to Identify and Report if Their Enterprise Assets are Missing Security Updates',\n  description = 'Train workforce to understand how to verify and report out-of-date software patches or any failures in automated processes and tools. Part of this training should include notifying IT personnel of any failures in automated processes and tools.',\n  updated_at = NOW()\nWHERE id = '7e333269-dd25-4934-9a87-f897f5372e4f';

-- Update 12.1: Ensure Network Infrastructure is Up-to-Date...\nUPDATE requirements_library SET\n  title = 'Ensure Network Infrastructure is Up-to-Date',\n  description = 'Ensure network infrastructure is kept up-to-date. Example implementations include running the latest stable release of software and/or using currently supported network-infrastructure devices.',\n  updated_at = NOW()\nWHERE id = 'c3e96c0c-5d51-4c4d-977c-27ef124f0587';

-- Update 14.1: Establish and Maintain a Security Awareness Program...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Security Awareness Program',\n  description = 'Establish and maintain a security awareness program. The purpose of a security awareness program is to educate the enterprise''s workforce on how to interact with enterprise assets and data in a secure manner. Review and update documentation annually, or when significant enterprise changes occur that could impact this Safeguard.',\n  updated_at = NOW()\nWHERE id = '9958f66e-7d80-4c10-a3f3-fefea3b5cdc9';

-- Update 12.2: Establish and Maintain a Secure Network Architecture...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Secure Network Architecture',\n  description = 'Establish and maintain a secure network architecture. A secure network architecture must address segmentation, least privilege, and availability, at a minimum.',\n  updated_at = NOW()\nWHERE id = '74aa97a2-71b0-4de1-94c3-dc7f20ebbaa9';

-- Update 2.3: Address Unauthorized Software...\nUPDATE requirements_library SET\n  title = 'Address Unauthorized Software',\n  description = 'Ensure that unauthorized software is either removed from use on enterprise assets or receives a documented exception. Review monthly, or more frequently.',\n  updated_at = NOW()\nWHERE id = '269b5027-bfad-40dc-94d8-587dfbc95c09';

-- Update 5.3: Disable Dormant Accounts...\nUPDATE requirements_library SET\n  title = 'Disable Dormant Accounts',\n  description = 'Delete or disable any dormant accounts after a period of 45 days of inactivity, where supported.',\n  updated_at = NOW()\nWHERE id = '5b6d3f44-cd2c-4ddf-aae5-ef9f880ee9ed';

-- Update 10.2: Configure Automatic Anti-Malware Signature Updates...\nUPDATE requirements_library SET\n  title = 'Configure Automatic Anti-Malware Signature Updates',\n  description = 'Configure automatic anti-malware signature updates on all enterprise assets.',\n  updated_at = NOW()\nWHERE id = '78f53f47-eca0-4e93-98b7-64bcdfc70ee6';

-- Update 1.3: Utilize an Active Discovery Tool...\nUPDATE requirements_library SET\n  title = 'Utilize an Active Discovery Tool',\n  description = 'Utilize an active discovery tool to identify assets connected to the enterprise''s network. Configure the active discovery tool to execute daily, or more frequently.',\n  updated_at = NOW()\nWHERE id = 'f9d5a9af-11f6-4cd6-940b-5343ac806659';