-- Update 13.6: Collect Network Traffic Flow Logs...\nUPDATE requirements_library SET\n  title = 'Collect Network Traffic Flow Logs',\n  description = 'Collect network traffic flow logs and/or network traffic to review and alert upon. Logs useful for incident response are NetFlow, SFlow, and IPFIX.',\n  updated_at = NOW()\nWHERE id = '4ad5b03d-1908-4f75-bc34-158b68a5d28c';

-- Update 18.1: Establish and Maintain a Penetration Testing Program...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Penetration Testing Program',\n  description = 'Establish and maintain a penetration testing program appropriate to the size, complexity, and maturity of the enterprise. Penetration testing program characteristics include scope, such as network, web application, Application Programming Interface (API), hosted services, and physical premise controls; frequency; limitations, such as acceptable hours, and excluded attack types; point of contact information; remediation, such as how findings will be routed internally; and retrospective requirements.',\n  updated_at = NOW()\nWHERE id = 'e683c55e-7075-49a7-8ec9-69c48c8c8d3d';

-- Update 13.5: Manage Access Control for Remote Assets...\nUPDATE requirements_library SET\n  title = 'Manage Access Control for Remote Assets',\n  description = 'Manage access control for assets remotely connecting to enterprise resources. Determine amount of access to enterprise resources based on: up-to-date anti-malware software installed, patch level of the operating system and applications, integrity of those applications, and proper configuration.',\n  updated_at = NOW()\nWHERE id = 'b7cd1bb3-3aa7-454c-8586-6c767c3c3433';

-- Update 6.4: Require MFA for Remote Network Access...\nUPDATE requirements_library SET\n  title = 'Require MFA for Remote Network Access',\n  description = 'Require all users to use multi-factor authentication (MFA) for remote network access.',\n  updated_at = NOW()\nWHERE id = 'ad8b5dcb-7469-4f39-9328-44d492357d55';

-- Update 6.3: Require MFA for Externally-Exposed Applications...\nUPDATE requirements_library SET\n  title = 'Require MFA for Externally-Exposed Applications',\n  description = 'Require all users to use multi-factor authentication (MFA) for externally-exposed enterprise or third-party applications.',\n  updated_at = NOW()\nWHERE id = '92b79f31-9bfe-4748-9c8b-21be13b6d7a0';

-- Update 4.10: Enforce Automatic Device Lockout on Portable End-User Device...\nUPDATE requirements_library SET\n  title = 'Enforce Automatic Device Lockout on Portable End-User Devices',\n  description = 'Enforce automatic device lockout following a predetermined threshold of invalid authentication attempts. Automatic lockout must be enforced across portable end-user devices, where supported. For laptops and workstations, apply automatic lockout for a minimum of 30 minutes or until an administrator unlocks the machine. For mobile devices, apply permanent lockout, or automatic lockout for a minimum of 1 hour.',\n  updated_at = NOW()\nWHERE id = '0100d42a-fe9f-4b85-8217-382fa76f4d62';

-- Update 6.5: Require MFA for Administrative Access...\nUPDATE requirements_library SET\n  title = 'Require MFA for Administrative Access',\n  description = 'Require multi-factor authentication (MFA) for access to enterprise assets with administrative privileges.',\n  updated_at = NOW()\nWHERE id = 'a36ca20d-8d9d-411c-b2cc-84753f172a00';

-- Update 15.1: Establish and Maintain an Inventory of Service Providers...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain an Inventory of Service Providers',\n  description = 'Establish and maintain an inventory of authorized service providers. The inventory is to list all approved service providers, vendor type, date of vendor approval, nature of services provided, and approved by authority. Review and update the inventory annually, or when significant enterprise changes occur that could impact this Safeguard.',\n  updated_at = NOW()\nWHERE id = '84a15036-0c17-423e-bb13-4bbbf9fefcf3';