-- Update 2.7: Allowlist Authorized Scripts...\nUPDATE requirements_library SET\n  title = 'Allowlist Authorized Scripts',\n  description = 'Allowlist authorized scripts that are allowed to run on enterprise assets. Implementation: Identify and approve all authorized scripts. Implement script execution controls and allowlisting. Monitor script execution activities. Establish secure script development procedures.',\n  updated_at = NOW()\nWHERE id = '618e32ac-1b74-4a3e-be94-cc1f029def85';

-- Update 3.3: Configure Data Access Control Lists...\nUPDATE requirements_library SET\n  title = 'Configure Data Access Control Lists',\n  description = 'Configure data access control lists based on a user''s need to know. Apply data access control lists, also known as access permissions, to local and remote file systems, databases, and applications.',\n  updated_at = NOW()\nWHERE id = '4896fcbf-0439-452c-a0bd-d38efd3ce825';

-- Update 3.11: Encrypt Sensitive Data at Rest...\nUPDATE requirements_library SET\n  title = 'Encrypt Sensitive Data at Rest',\n  description = 'Encrypt sensitive data at rest on servers, applications, and databases containing sensitive data. Storage-layer encryption, also known as server-side encryption, meets the intent of this Safeguard. Additional encryption methods may include application-layer encryption, also known as client-side encryption, where access to the data storage device(s) does not permit access to the plain-text data.',\n  updated_at = NOW()\nWHERE id = '8ae7a730-bbac-49b6-9e44-2d8d6b3176aa';

-- Update 3.12: Segment Data Processing and Storage Based on Sensitivity...\nUPDATE requirements_library SET\n  title = 'Segment Data Processing and Storage Based on Sensitivity',\n  description = 'Segment data processing and storage based on the sensitivity of the data. Do not process sensitive data on enterprise assets intended for lower sensitivity data.',\n  updated_at = NOW()\nWHERE id = '1414c93e-9343-4ad2-a000-ec6d2cc36cd0';

-- Update 16.2: Establish and Maintain a Process to Accept and Address Softw...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Process to Accept and Address Software Vulnerabilities',\n  description = 'Establish and maintain a process to accept and address reports of software vulnerabilities, including public disclosure of enterprise software vulnerabilities. The process is to include such items as: a vulnerability disclosure policy, a method for external entities to contact the enterprise to report vulnerabilities in enterprise software, a process for assessing, prioritizing, and tracking vulnerabilities, and a process for releasing updates to address vulnerabilities.',\n  updated_at = NOW()\nWHERE id = '4d556cc9-22d3-4a69-a1bc-2d0ad17b91ef';

-- Update 1.2: Address Unauthorized Assets...\nUPDATE requirements_library SET\n  title = 'Address Unauthorized Assets',\n  description = 'Ensure that a process exists to address unauthorized assets on a weekly basis. The enterprise may choose to remove the asset from the network, deny the asset from connecting remotely to the network, or quarantine the asset.',\n  updated_at = NOW()\nWHERE id = 'a589e898-3001-435b-b8e0-db82eb4bdb83';

-- Update 1.5: Use a Passive Asset Discovery Tool...\nUPDATE requirements_library SET\n  title = 'Use a Passive Asset Discovery Tool',\n  description = 'Use a passive discovery tool to identify assets connected to the enterprise network. Implementation: Deploy passive network monitoring tools. Analyze network traffic to identify connected devices. Detect assets without active scanning. Maintain continuous visibility of network-connected assets.',\n  updated_at = NOW()\nWHERE id = '5cd2c0a1-965b-464a-b775-3f795f41c5d4';

-- Update 2.4: Utilize Automated Software Inventory Tools...\nUPDATE requirements_library SET\n  title = 'Utilize Automated Software Inventory Tools',\n  description = 'Utilize automated software inventory tools throughout the enterprise. Implementation: Deploy enterprise-wide automated software inventory solutions. Configure tools for comprehensive software discovery. Integrate with configuration management systems. Automate software compliance monitoring and reporting.',\n  updated_at = NOW()\nWHERE id = '98db6e8a-1cff-4cfa-84be-614365627a1d';