-- Update 4.6: Securely Manage Enterprise Assets and Software...\nUPDATE requirements_library SET\n  title = 'Securely Manage Enterprise Assets and Software',\n  description = 'Securely manage enterprise assets and software. Example implementations include managing configuration through version-controlled-infrastructure-as-code and accessing administrative interfaces over secure network protocols, such as Secure Shell (SSH) and Hypertext Transfer Protocol Secure (HTTPS). Do not use insecure management protocols, such as Telnet and Hypertext Transfer Protocol (HTTP), unless operationally essential.',\n  updated_at = NOW()\nWHERE id = 'aa781ea6-eddf-4760-9032-5ff37f4203c8';

-- Update 4.8: Uninstall or Disable Unnecessary Services on Enterprise Asse...\nUPDATE requirements_library SET\n  title = 'Uninstall or Disable Unnecessary Services on Enterprise Assets and Software',\n  description = 'Uninstall or disable unnecessary services on enterprise assets and software, such as an unused file sharing service, web application module, or service function.',\n  updated_at = NOW()\nWHERE id = 'c9d0638a-4c56-4482-8b3b-6b768b93da8e';

-- Update 4.9: Configure Trusted DNS Servers on Enterprise Assets...\nUPDATE requirements_library SET\n  title = 'Configure Trusted DNS Servers on Enterprise Assets',\n  description = 'Configure trusted DNS servers on enterprise assets. Example implementations include: configuring assets to use enterprise-controlled DNS servers and/or reputable externally accessible DNS servers.',\n  updated_at = NOW()\nWHERE id = '1486d1ae-1f53-4f69-9069-1405c24b6c48';

-- Update 5.6: Centralize Account Management...\nUPDATE requirements_library SET\n  title = 'Centralize Account Management',\n  description = 'Centralize account management through a directory service.',\n  updated_at = NOW()\nWHERE id = '5a6abbce-725d-4c41-9be8-cc024099f700';

-- Update 6.8: Define and Maintain Role-Based Access Control...\nUPDATE requirements_library SET\n  title = 'Define and Maintain Role-Based Access Control',\n  description = 'Define and maintain role-based access control, through determining and documenting the access rights necessary for each role within the enterprise to successfully carry out their assigned duties. Perform access control reviews of enterprise assets to validate that all privileges are authorized, on a recurring schedule at a minimum annually, or more frequently.',\n  updated_at = NOW()\nWHERE id = '3a53c5c4-81d8-4892-9818-d4c11f2f78f8';

-- Update 17.8: Conduct Post-Incident Reviews...\nUPDATE requirements_library SET\n  title = 'Conduct Post-Incident Reviews',\n  description = 'Conduct post-incident reviews. Post-incident reviews help prevent recurrence of incidents, as well as improve security practices.',\n  updated_at = NOW()\nWHERE id = 'b00ad0ed-c3ab-42e7-9079-013abce6b52b';

-- Update 16.12: Implement Code-Level Security Checks...\nUPDATE requirements_library SET\n  title = 'Implement Code-Level Security Checks',\n  description = 'Apply static and dynamic analysis security testing tools to verify that secure coding practices are being adhered to for internally developed software.',\n  updated_at = NOW()\nWHERE id = '8f0280c8-0a50-4582-80cd-7ab8fee7026e';

-- Update 16.9: Train Developers in Application Security Concepts and Secure...\nUPDATE requirements_library SET\n  title = 'Train Developers in Application Security Concepts and Secure Coding',\n  description = 'Ensure that all software development personnel receive training in writing secure code for their specific development environment and responsibilities.',\n  updated_at = NOW()\nWHERE id = '4a22aaa4-f873-49f0-add2-f5277f4e2d75';