-- Update 5.30: ICT readiness for business continuity...\nUPDATE requirements_library SET\n  title = 'ICT readiness for business continuity',\n  description = 'ICT readiness shall be planned, implemented, maintained and tested based on business continuity objectives and ICT continuity requirements.',\n  updated_at = NOW()\nWHERE id = '29e3588c-76e3-46e5-a9b4-8ecd4d2ac123';

-- Update 5.31: Legal, statutory, regulatory and contractual requirements...\nUPDATE requirements_library SET\n  title = 'Legal, statutory, regulatory and contractual requirements',\n  description = 'Legal, statutory, regulatory and contractual requirements relevant to information security and the organization''s approach to meet these requirements shall be identified, documented and kept up to date.',\n  updated_at = NOW()\nWHERE id = '569d9c92-d1c1-4b03-821b-b4c572234e95';

-- Update 5.32: Intellectual property rights...\nUPDATE requirements_library SET\n  title = 'Intellectual property rights',\n  description = 'The organization shall implement appropriate procedures to protect intellectual property rights.',\n  updated_at = NOW()\nWHERE id = '88814f7a-0453-41fa-8d0e-22671b912cf7';

-- Update 5.33: Protection of records...\nUPDATE requirements_library SET\n  title = 'Protection of records',\n  description = 'Records shall be protected from loss, destruction, falsification, unauthorized access and unauthorized release.',\n  updated_at = NOW()\nWHERE id = '1eca7a8d-01c9-4228-b2f7-ffc048432650';

-- Update 5.34: Privacy and protection of personally identifiable informatio...\nUPDATE requirements_library SET\n  title = 'Privacy and protection of personally identifiable information',\n  description = 'The organization shall identify and meet the requirements regarding the preservation of privacy and protection of personally identifiable information according to applicable laws and regulations and contractual requirements.',\n  updated_at = NOW()\nWHERE id = '38232c99-730c-458f-952f-d11dad5f856a';

-- Update 5.35: Independent review of information security...\nUPDATE requirements_library SET\n  title = 'Independent review of information security',\n  description = 'The organization''s approach to managing information security and its implementation shall be reviewed independently at planned intervals or when significant changes occur.',\n  updated_at = NOW()\nWHERE id = 'd525bd65-9a39-40f6-955d-372e18a3ed1a';

-- Update 5.36: Compliance with policies, rules and standards for informatio...\nUPDATE requirements_library SET\n  title = 'Compliance with policies, rules and standards for information security',\n  description = 'Compliance with the organization''s information security policy, topic-specific policies, rules and standards shall be regularly reviewed.',\n  updated_at = NOW()\nWHERE id = '5b6f96dd-19da-4bab-9d62-83f80db69e41';

-- Update 5.37: Documented operating procedures...\nUPDATE requirements_library SET\n  title = 'Documented operating procedures',\n  description = 'Operating procedures for information processing facilities shall be documented and made available to personnel who need them.',\n  updated_at = NOW()\nWHERE id = '2554f2ea-5f2c-47df-9a1e-ac3ee9a25a5a';