-- Update 3.7: Establish and Maintain a Data Classification Scheme...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Data Classification Scheme',\n  description = 'Establish and maintain an enterprise data classification scheme that includes, at a minimum, sensitive data.',\n  updated_at = NOW()\nWHERE id = 'bd278276-b064-412d-8e35-77c7fd2ceb1d';

-- Update 3.8: Document Data Flows...\nUPDATE requirements_library SET\n  title = 'Document Data Flows',\n  description = 'Document data flows. Data flow documentation includes service provider data flows and should be based on the enterprise''s data inventory.',\n  updated_at = NOW()\nWHERE id = '8a29b2e8-bc35-43cf-90a2-448458f656cb';

-- Update 3.9: Encrypt Data on Removable Media...\nUPDATE requirements_library SET\n  title = 'Encrypt Data on Removable Media',\n  description = 'Encrypt data on removable media.',\n  updated_at = NOW()\nWHERE id = '4c198478-2641-4ee8-a237-5d4a4139b784';

-- Update 1.1: Establish and Maintain Detailed Enterprise Asset Inventory...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain Detailed Enterprise Asset Inventory',\n  description = 'Establish and maintain an accurate, detailed, and up-to-date inventory of all enterprise assets with the potential to store or process data, to include: end-user devices (including portable and mobile), network devices, non-computing/IoT devices, and servers. Ensure the inventory records the network address (if static), hardware address, machine name, enterprise asset owner, department for each asset, and whether the asset has been approved to connect to the network. For mobile end-user devices, MDM type tools can support this process, where appropriate. This inventory includes assets connected to the infrastructure physically, virtually, remotely, and those within cloud environments. Additionally, it includes assets that are regularly connected to the enterprise''s network infrastructure, even if they are not under control of the enterprise. Review and update the inventory of all enterprise assets bi-annually, or more frequently.',\n  updated_at = NOW()\nWHERE id = 'd0cb1926-1c0f-4bd7-9812-43153c625238';

-- Update 1.2: Address Unauthorized Assets...\nUPDATE requirements_library SET\n  title = 'Address Unauthorized Assets',\n  description = 'Ensure that a process exists to address unauthorized assets on a weekly basis. The enterprise may choose to remove the asset from the network, deny the asset from connecting remotely to the network, or quarantine the asset.',\n  updated_at = NOW()\nWHERE id = '7d23c2e9-b980-49d4-a62a-15e40bb3d575';

-- Update 2.1: Establish and Maintain a Software Inventory...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Software Inventory',\n  description = 'Establish and maintain a detailed inventory of all licensed software installed on enterprise assets. The software inventory must document the title, publisher, initial install/use date, and business purpose for each entry; where appropriate, include the Uniform Resource Locator (URL), app store(s), version(s), deployment mechanism, decommission date, and number of licenses. Review and update the software inventory bi-annually, or more frequently.',\n  updated_at = NOW()\nWHERE id = 'aaf3e06e-7c27-4fd0-a79b-b8ac653e7c60';

-- Update 2.2: Ensure Authorized Software is Currently Supported...\nUPDATE requirements_library SET\n  title = 'Ensure Authorized Software is Currently Supported',\n  description = 'Ensure that only currently supported software is designated as authorized in the software inventory for enterprise assets. If software is unsupported, yet necessary for the fulfillment of the enterprise''s mission, document an exception detailing mitigating controls and residual risk acceptance. For any unsupported software without an exception documentation, designate as unauthorized. Review the software list to verify software support at least monthly, or more frequently.',\n  updated_at = NOW()\nWHERE id = 'f0baee5a-6ecb-427e-b79e-52c2629fa2ac';

-- Update 15.2: Establish and Maintain a Service Provider Management Policy...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Service Provider Management Policy',\n  description = 'Establish and maintain a policy for managing service providers that includes a risk assessment, business purpose and mission alignment, contractual requirements for security, privacy expectations, and remediation processes. The policy shall mandate minimum security requirements for all service providers. Review and update the policy annually, or when significant enterprise changes occur.',\n  updated_at = NOW()\nWHERE id = '8f7cc0b4-4305-4cd7-9295-fea7e742c3ed';