-- Update 8.1: Establish and Maintain an Audit Log Management Process...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain an Audit Log Management Process',\n  description = 'Establish and maintain an audit log management process that defines the enterprise''s logging requirements. At a minimum, address the collection, review, and retention of audit logs for enterprise assets. Review and update documentation annually, or when significant enterprise changes occur that could impact this Safeguard.',\n  updated_at = NOW()\nWHERE id = 'b41c0e79-7f99-476f-a4c4-1bf260623709';

-- Update 7.2: Establish and Maintain a Remediation Process...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Remediation Process',\n  description = 'Establish and maintain a documented remediation process for enterprise assets with a vulnerability management process.',\n  updated_at = NOW()\nWHERE id = 'ca59c87c-a820-4aa1-8f47-4b808401db5a';

-- Update 8.10: Retain Audit Logs...\nUPDATE requirements_library SET\n  title = 'Retain Audit Logs',\n  description = 'Retain audit logs across enterprise assets for a minimum of 90 days.',\n  updated_at = NOW()\nWHERE id = 'd3c1ebe0-57c6-46c4-9488-c2c144fa2b75';

-- Update 7.6: Perform Automated Vulnerability Scans of Externally-Exposed ...\nUPDATE requirements_library SET\n  title = 'Perform Automated Vulnerability Scans of Externally-Exposed Enterprise Assets',\n  description = 'Perform automated vulnerability scans of externally-exposed enterprise assets using either an internal or external scanning utility. Perform scans on a monthly, or more frequent, basis.',\n  updated_at = NOW()\nWHERE id = '6b9ed678-dd08-433a-96cb-a3060e01ca91';

-- Update 7.7: Remediate Detected Vulnerabilities...\nUPDATE requirements_library SET\n  title = 'Remediate Detected Vulnerabilities',\n  description = 'Remediate detected vulnerabilities in software through processes and tooling on a monthly, or more frequent, basis, based on the remediation process.',\n  updated_at = NOW()\nWHERE id = 'f41ce6fb-718d-4b81-ab83-6903bae55c91';

-- Update 7.3: Perform Automated Operating System Patch Management...\nUPDATE requirements_library SET\n  title = 'Perform Automated Operating System Patch Management',\n  description = 'Perform operating system updates on enterprise assets through automated patch management on a monthly, or more frequent, basis.',\n  updated_at = NOW()\nWHERE id = 'c8d4d0fd-dcab-4117-8558-600c3460fd8a';

-- Update 7.4: Perform Automated Application Patch Management...\nUPDATE requirements_library SET\n  title = 'Perform Automated Application Patch Management',\n  description = 'Perform application updates on enterprise assets through automated patch management on a monthly, or more frequent, basis.',\n  updated_at = NOW()\nWHERE id = '925d3e8b-4749-4e45-88e7-59c746597c5c';

-- Update 8.5: Collect Detailed Audit Logs...\nUPDATE requirements_library SET\n  title = 'Collect Detailed Audit Logs',\n  description = 'Configure detailed audit logging for enterprise assets containing sensitive data. Include event date, timestamp, source addresses, destination addresses, usernames, and process names associated with the event.',\n  updated_at = NOW()\nWHERE id = '93b745ec-1e8f-475b-afd3-377d8312207c';