-- Update 8.1: Establish and Maintain an Audit Log Management Process...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain an Audit Log Management Process',\n  description = 'Establish and maintain an audit log management process that defines the enterprise''s logging requirements. At a minimum, address the collection, review, and retention of audit logs for enterprise assets. Review and update documentation annually, or when significant enterprise changes occur that could impact this Safeguard.',\n  updated_at = NOW()\nWHERE id = 'fc47b710-e2a6-4c5c-90ab-46512cc03574';

-- Update 8.11: Conduct Audit Log Reviews...\nUPDATE requirements_library SET\n  title = 'Conduct Audit Log Reviews',\n  description = 'Conduct reviews of audit logs to detect anomalies or abnormal events that could indicate a potential threat. Conduct reviews on a weekly basis.',\n  updated_at = NOW()\nWHERE id = 'dee725e7-a9ed-4db0-b875-206b2a04102a';

-- Update 6.1: Establish an Access Granting Process...\nUPDATE requirements_library SET\n  title = 'Establish an Access Granting Process',\n  description = 'Establish and follow a process for granting access to enterprise assets upon new hire, promotion, or role change of a user.',\n  updated_at = NOW()\nWHERE id = 'c8503c75-d131-4c86-af74-e9a7dffb3da2';

-- Update 8.12: Collect Service Provider Logs...\nUPDATE requirements_library SET\n  title = 'Collect Service Provider Logs',\n  description = 'Collect service provider logs. Example implementations include collecting authentication and authorization events, data creation and disposal events, and user management events.',\n  updated_at = NOW()\nWHERE id = '33c6f819-6af2-4519-aff1-33ed91705796';

-- Update 6.3: Require MFA for Externally-Exposed Applications...\nUPDATE requirements_library SET\n  title = 'Require MFA for Externally-Exposed Applications',\n  description = 'Require all users to use multi-factor authentication (MFA) for externally-exposed enterprise or third-party applications.',\n  updated_at = NOW()\nWHERE id = '928c24ee-0b6b-4d85-baef-88cdfe900f85';

-- Update 7.1: Establish and Maintain a Vulnerability Management Process...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Vulnerability Management Process',\n  description = 'Establish and maintain a documented vulnerability management process for enterprise assets. Review and update documentation annually, or when significant enterprise changes occur that could impact this Safeguard.',\n  updated_at = NOW()\nWHERE id = '73ffec29-b8f0-43b5-a165-53d232548795';

-- Update 7.9: Security of assets off-premises...\nUPDATE requirements_library SET\n  title = 'Security of assets off-premises',\n  description = 'Off-site assets shall be protected.',\n  updated_at = NOW()\nWHERE id = 'f11bee6c-4635-4993-9e11-55d43b79186b';

-- Update 8.3: Ensure Adequate Audit Log Storage...\nUPDATE requirements_library SET\n  title = 'Ensure Adequate Audit Log Storage',\n  description = 'Ensure that logging destinations maintain adequate storage to comply with the enterprise''s audit log management process.',\n  updated_at = NOW()\nWHERE id = '4a5848f3-7a5f-4c9a-91b8-6231c1826931';