-- Update 16.5: Use Up-to-Date and Trusted Third-Party Software Components...\nUPDATE requirements_library SET\n  title = 'Use Up-to-Date and Trusted Third-Party Software Components',\n  description = 'Use up-to-date and trusted third-party software components. When possible, choose established and proven frameworks and libraries that provide adequate security. Components that are not supported with timely security updates should be replaced with alternative components.',\n  updated_at = NOW()\nWHERE id = '96fe9e20-79ec-47a5-8b83-c6e127c77e55';

-- Update 3.5: Securely Dispose of Data...\nUPDATE requirements_library SET\n  title = 'Securely Dispose of Data',\n  description = 'Securely dispose of data as outlined in the enterprise''s data management process. Ensure the disposal process and method are commensurate with the data sensitivity.',\n  updated_at = NOW()\nWHERE id = '08280542-683f-4cb1-8632-b7294a5d5c99';

-- Update 3.6: Encrypt Data on End-User Devices...\nUPDATE requirements_library SET\n  title = 'Encrypt Data on End-User Devices',\n  description = 'Encrypt data on end-user devices containing sensitive data. Example implementations can include: Windows BitLocker®, Apple FileVault®, Linux dm-crypt.',\n  updated_at = NOW()\nWHERE id = 'c3043a01-2cfc-447e-8325-5be2557391c0';

-- Update 16.10: Apply Secure Design Principles in Application Architectures...\nUPDATE requirements_library SET\n  title = 'Apply Secure Design Principles in Application Architectures',\n  description = 'Apply secure design principles in application architectures. Secure design principles include the concept of least privilege, fail-safe defaults, separation of duties, defense-in-depth, and zero trust.',\n  updated_at = NOW()\nWHERE id = 'b00898d8-ffe6-49fb-aacd-a40d4bfed203';

-- Update 16.8: Separate Production and Non-Production Systems...\nUPDATE requirements_library SET\n  title = 'Separate Production and Non-Production Systems',\n  description = 'Maintain separate environments for production and non-production systems. Developers should not have unmonitored access to production environments.',\n  updated_at = NOW()\nWHERE id = '24b71720-6628-471d-8e3f-1ffc045344d5';

-- Update 15.4: Ensure Service Provider Contracts Include Security Requireme...\nUPDATE requirements_library SET\n  title = 'Ensure Service Provider Contracts Include Security Requirements',\n  description = 'Ensure that service provider contracts include security requirements. Examples include notification for information security events, assessment and testing requirements, restrictions on personnel and service providers, intellectual property protection, and right to audit.',\n  updated_at = NOW()\nWHERE id = '8513ae9c-0359-4b32-8b25-5fc7d3f82cc8';

-- Update 15.5: Assess Service Providers...\nUPDATE requirements_library SET\n  title = 'Assess Service Providers',\n  description = 'Assess service providers consistent with the enterprise''s service provider policy. Assessment scope may vary based on classification from Safeguard 15.3, and may include review of standardized assessment reports, such as Service Organization Control 2 (SOC 2) Type 2 reports.',\n  updated_at = NOW()\nWHERE id = '7892d25b-f3de-4ded-ab1b-1350a9ff6c1b';

-- Update 8.11: Conduct Audit Log Reviews...\nUPDATE requirements_library SET\n  title = 'Conduct Audit Log Reviews',\n  description = 'Conduct reviews of audit logs to detect anomalies or abnormal events that could indicate a potential threat. Conduct reviews on a weekly basis.',\n  updated_at = NOW()\nWHERE id = '202661db-de3d-4a2f-8cb5-ca3dff78959e';