-- Update 14.8: Train Workforce on the Dangers of Connecting to and Transmit...\nUPDATE requirements_library SET\n  title = 'Train Workforce on the Dangers of Connecting to and Transmitting Enterprise Data Over Insecure Networks',\n  description = 'Train workforce on the dangers of connecting to and transmitting enterprise data over insecure networks. Implementation: Educate users on network security risks and threats. Provide training on secure network connection practices. Train on VPN usage and secure communication protocols. Monitor network usage and provide security guidance.',\n  updated_at = NOW()\nWHERE id = '172a089f-d2ac-460d-9da3-0f55ac9e244e';

-- Update 8.3: Ensure Adequate Audit Log Storage...\nUPDATE requirements_library SET\n  title = 'Ensure Adequate Audit Log Storage',\n  description = 'Ensure that logging destinations maintain adequate storage to comply with the enterprise''s audit log management process.',\n  updated_at = NOW()\nWHERE id = 'a7b80060-9221-4352-ba04-0a8a787c948c';

-- Update 9.1: Ensure Use of Only Fully Supported Browsers and Email Client...\nUPDATE requirements_library SET\n  title = 'Ensure Use of Only Fully Supported Browsers and Email Clients',\n  description = 'Ensure only fully supported browsers and email clients are allowed to execute in the enterprise, only using the latest version of browsers and email clients provided by the vendor.',\n  updated_at = NOW()\nWHERE id = '75c3ae1b-c5e5-43b3-88dc-4d3273a3e72f';

-- Update 13.11: Tune Security Event Alerting Thresholds...\nUPDATE requirements_library SET\n  title = 'Tune Security Event Alerting Thresholds',\n  description = 'Tune security event alerting thresholds monthly, or more frequently.',\n  updated_at = NOW()\nWHERE id = '6ac04ca2-07fb-4987-ab32-323e47192e9b';

-- Update 13.4: Perform Traffic Filtering Between Network Segments...\nUPDATE requirements_library SET\n  title = 'Perform Traffic Filtering Between Network Segments',\n  description = 'Perform traffic filtering between network segments, where appropriate.',\n  updated_at = NOW()\nWHERE id = '2641a448-aac9-40ef-aaf9-35620a80b5ca';

-- Update 12.6: Use of Secure Network Management and Communication Protocols...\nUPDATE requirements_library SET\n  title = 'Use of Secure Network Management and Communication Protocols',\n  description = 'Use secure network management and communication protocols (e.g., 802.1X, Wi-Fi Protected Access 2 (WPA2) Enterprise or Wi-Fi Protected Access 3 (WPA3)).',\n  updated_at = NOW()\nWHERE id = '23cf903e-f98b-44a1-8898-7878ce28bac6';

-- Update 12.5: Centralize Network Authentication, Authorization, and Auditi...\nUPDATE requirements_library SET\n  title = 'Centralize Network Authentication, Authorization, and Auditing (AAA)',\n  description = 'Centralize network Authentication, Authorization, and Auditing (AAA).',\n  updated_at = NOW()\nWHERE id = 'f9b7ce9f-36da-44d5-a05b-d6633a8b93ba';

-- Update 11.5: Test Data Recovery...\nUPDATE requirements_library SET\n  title = 'Test Data Recovery',\n  description = 'Test backup and recovery of enterprise data on an annual basis. Testing shall include restoration of backup data to a separate system, and a test of the time required to restore from backup. Document and review test results.',\n  updated_at = NOW()\nWHERE id = 'c76a22a6-71e2-4a92-8da1-7b4b73cf7131';