-- Update 11.2: Perform Automated Backups...\nUPDATE requirements_library SET\n  title = 'Perform Automated Backups',\n  description = 'Perform automated backups of in-scope enterprise assets. Run backups weekly, or more frequently, using an automated process.',\n  updated_at = NOW()\nWHERE id = '20c5d88b-f415-4521-ac3a-44ef3301bf4c';

-- Update 3.2: Establish and Maintain a Data Inventory...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Data Inventory',\n  description = 'Establish and maintain a documented data inventory based on the enterprise''s data management process. Inventory data with a sensitivity of high or very high, or data subject to regulatory requirements. The inventory shall include location, volume, sensitivity, owner, custodian, cloud service provider used, and determine if the location is a new location for the enterprise.',\n  updated_at = NOW()\nWHERE id = 'e9269a86-166c-4081-8ccc-4d68c456925b';

-- Update 2.3: Address Unauthorized Software...\nUPDATE requirements_library SET\n  title = 'Address Unauthorized Software',\n  description = 'Ensure that unauthorized software is either removed from use on enterprise assets or receives a documented exception. Review monthly, or more frequently.',\n  updated_at = NOW()\nWHERE id = '22ab120e-3236-4852-8d45-e9b4cb55ed5f';

-- Update 14.2: Train Workforce Members to Recognize Social Engineering Atta...\nUPDATE requirements_library SET\n  title = 'Train Workforce Members to Recognize Social Engineering Attacks',\n  description = 'Train workforce members to recognize social engineering attacks, such as phishing, pretexting, and tailgating.',\n  updated_at = NOW()\nWHERE id = '6bc9165b-276a-4940-8619-664779d793f4';

-- Update 14.6: Train Workforce Members on Recognizing and Reporting Securit...\nUPDATE requirements_library SET\n  title = 'Train Workforce Members on Recognizing and Reporting Security Incidents',\n  description = 'Train workforce members to be able to recognize a potential incident and be able to report such an incident.',\n  updated_at = NOW()\nWHERE id = '69fc5016-4427-4e13-800b-667a67b634cf';

-- Update 11.1: Establish and Maintain a Data Recovery Process...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Data Recovery Process',\n  description = 'Establish and maintain a data recovery process. In the process, address the scope of data recovery activities, recovery prioritization, and the roles and responsibilities of designated personnel. Review and update documentation annually, or when significant enterprise changes occur that could impact this Safeguard.',\n  updated_at = NOW()\nWHERE id = '6469f625-bde6-48c7-bb29-418b936100e0';

-- Update 11.4: Establish and Maintain an Isolated Instance of Recovery Data...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain an Isolated Instance of Recovery Data',\n  description = 'Establish and maintain an isolated instance of recovery data. Example implementations include, version controlling backup destinations through offline, cloud, or off-site systems or services.',\n  updated_at = NOW()\nWHERE id = '0b9f7d7e-2856-4c74-9533-f2589fb73f46';

-- Update 2.4: Utilize Automated Software Inventory Tools...\nUPDATE requirements_library SET\n  title = 'Utilize Automated Software Inventory Tools',\n  description = 'Utilize software inventory tools, when possible, throughout the enterprise to automate the discovery and documentation of installed software.',\n  updated_at = NOW()\nWHERE id = '869d44d0-4daa-4e90-b679-a854f8c2591e';