-- Update 8.3: Ensure Adequate Audit Log Storage...\nUPDATE requirements_library SET\n  title = 'Ensure Adequate Audit Log Storage',\n  description = 'Ensure that logging destinations maintain adequate storage to comply with the enterprise''s audit log management process.',\n  updated_at = NOW()\nWHERE id = '923da82f-3ef4-40df-9ae0-f6466a72fb5a';

-- Update 10.1: Deploy and Maintain Anti-Malware Software...\nUPDATE requirements_library SET\n  title = 'Deploy and Maintain Anti-Malware Software',\n  description = 'Deploy and maintain anti-malware software on all enterprise assets.',\n  updated_at = NOW()\nWHERE id = '978f46dd-49ac-467b-bc4f-d8223c9b05f4';

-- Update 10.3: Disable Autorun and Autoplay for Removable Media...\nUPDATE requirements_library SET\n  title = 'Disable Autorun and Autoplay for Removable Media',\n  description = 'Disable autorun and autoplay auto-execute functionality for removable media.',\n  updated_at = NOW()\nWHERE id = '3d73a8cf-1782-46df-99e5-767073a34a94';

-- Update 11.1: Establish and Maintain a Data Recovery Process...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Data Recovery Process',\n  description = 'Establish and maintain a data recovery process. In the process, address the scope of data recovery activities, recovery prioritization, and the roles and responsibilities of designated personnel. Review and update documentation annually, or when significant enterprise changes occur that could impact this Safeguard.',\n  updated_at = NOW()\nWHERE id = 'fc2af9b5-b41a-4b5f-92ea-65886a214ab6';

-- Update 11.2: Perform Automated Backups...\nUPDATE requirements_library SET\n  title = 'Perform Automated Backups',\n  description = 'Perform automated backups of in-scope enterprise assets. Run backups weekly, or more frequently, using an automated process.',\n  updated_at = NOW()\nWHERE id = 'd53f243f-a783-4975-94f4-5861f9134e75';

-- Update 11.4: Establish and Maintain an Isolated Instance of Recovery Data...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain an Isolated Instance of Recovery Data',\n  description = 'Establish and maintain an isolated instance of recovery data. Example implementations include, version controlling backup destinations through offline, cloud, or off-site systems or services.',\n  updated_at = NOW()\nWHERE id = '93b16ee5-f4b1-4cf4-81b1-abd87fccdcb1';

-- Update 14.6: Train Workforce Members on Recognizing and Reporting Securit...\nUPDATE requirements_library SET\n  title = 'Train Workforce Members on Recognizing and Reporting Security Incidents',\n  description = 'Train workforce members to be able to recognize a potential incident and be able to report such an incident.',\n  updated_at = NOW()\nWHERE id = '46cdb38a-acbb-430d-81a4-acbf68a429ff';

-- Update 14.8: Train Workforce on the Dangers of Connecting to and Transmit...\nUPDATE requirements_library SET\n  title = 'Train Workforce on the Dangers of Connecting to and Transmitting Enterprise Data Over Insecure Networks',\n  description = 'Train workforce members on the dangers of connecting to, and transmitting data over, insecure networks for enterprise activities. If the enterprise has remote workers, training must include guidance to ensure that all users securely configure their home network infrastructure.',\n  updated_at = NOW()\nWHERE id = '05b51229-2a54-4c64-8146-eabd67484eb8';