-- Update 16.14: Conduct Threat Modeling...\nUPDATE requirements_library SET\n  title = 'Conduct Threat Modeling',\n  description = 'Conduct threat modeling for applications to identify and address potential security weaknesses early in the development process.',\n  updated_at = NOW()\nWHERE id = 'c9571a12-88be-48aa-852b-64f8adb05b71';

-- Update 4.10: Enforce Automatic Device Lockout on Portable End-User Device...\nUPDATE requirements_library SET\n  title = 'Enforce Automatic Device Lockout on Portable End-User Devices',\n  description = 'Enforce automatic device lockout following a predetermined threshold of invalid authentication attempts. Automatic lockout must be enforced across portable end-user devices, where supported. For laptops and workstations, apply automatic lockout for a minimum of 30 minutes or until an administrator unlocks the machine. For mobile devices, apply permanent lockout, or automatic lockout for a minimum of 1 hour.',\n  updated_at = NOW()\nWHERE id = '1423965d-3d75-490e-b77a-c961891de26b';

-- Update 16.10: Apply Secure Design Principles in Application Architectures...\nUPDATE requirements_library SET\n  title = 'Apply Secure Design Principles in Application Architectures',\n  description = 'Apply secure design principles in application architectures. Secure design principles include the concept of least privilege, fail-safe defaults, separation of duties, defense-in-depth, and zero trust.',\n  updated_at = NOW()\nWHERE id = '7eb9e381-c1b9-474e-9a42-3cb562c21744';

-- Update 7.2: Establish and Maintain a Remediation Process...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Remediation Process',\n  description = 'Establish and maintain a documented remediation process for enterprise assets with a vulnerability management process.',\n  updated_at = NOW()\nWHERE id = 'f0f8953a-809b-450c-b856-8bc02d66243d';

-- Update 7.4: Perform Automated Application Patch Management...\nUPDATE requirements_library SET\n  title = 'Perform Automated Application Patch Management',\n  description = 'Perform application updates on enterprise assets through automated patch management on a monthly, or more frequent, basis.',\n  updated_at = NOW()\nWHERE id = '908b4a11-f3b7-405b-9549-0a3f630e5eff';

-- Update 16.8: Separate Production and Non-Production Systems...\nUPDATE requirements_library SET\n  title = 'Separate Production and Non-Production Systems',\n  description = 'Maintain separate environments for production and non-production systems. Developers should not have unmonitored access to production environments.',\n  updated_at = NOW()\nWHERE id = '84b2473f-a26b-425e-922e-4cfdb1f83b03';

-- Update 8.10: Retain Audit Logs...\nUPDATE requirements_library SET\n  title = 'Retain Audit Logs',\n  description = 'Retain audit logs across enterprise assets for a minimum of 90 days.',\n  updated_at = NOW()\nWHERE id = '8471a3b9-27ca-4c32-aa9b-e28ea2c9efa0';

-- Update 16.6: Establish and Maintain a Severity Rating System and Process ...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Severity Rating System and Process for Application Vulnerabilities',\n  description = 'Establish and maintain a severity rating system and process for application vulnerabilities that facilitates prioritizing the order in which discovered vulnerabilities are fixed. This process includes setting a minimum level of security acceptability for releasing code or applications.',\n  updated_at = NOW()\nWHERE id = '2056992c-366b-4f8a-8fc5-993aa77e11e8';