-- Update 16.4: Establish and Manage an Inventory of Third-Party Software Co...\nUPDATE requirements_library SET\n  title = 'Establish and Manage an Inventory of Third-Party Software Components',\n  description = 'Establish and manage an inventory of the enterprise''s third-party software components. Third-party software components must be documented with title, publisher, initial install/use date, and business purpose. For enterprise software deployed to enterprise assets, update and review the inventory of third-party software components monthly, or more frequently.',\n  updated_at = NOW()\nWHERE id = '6bb187b7-f209-4d22-9260-b100848aecb1';

-- Update 3.10: Encrypt Sensitive Data in Transit...\nUPDATE requirements_library SET\n  title = 'Encrypt Sensitive Data in Transit',\n  description = 'Encrypt sensitive data in transit. Example implementations can include: Transport Layer Security (TLS) and Open Secure Shell (OpenSSH).',\n  updated_at = NOW()\nWHERE id = '4f361d49-e7b4-4864-a8c3-939deb2c9bcf';

-- Update 3.12: Segment Data Processing and Storage Based on Sensitivity...\nUPDATE requirements_library SET\n  title = 'Segment Data Processing and Storage Based on Sensitivity',\n  description = 'Segment data processing and storage based on the sensitivity of the data. Do not process sensitive data on enterprise assets intended for lower sensitivity data.',\n  updated_at = NOW()\nWHERE id = '55bcb859-030e-4b2b-bf24-cbf7bf8f7cf1';

-- Update 16.9: Train Developers in Application Security Concepts and Secure...\nUPDATE requirements_library SET\n  title = 'Train Developers in Application Security Concepts and Secure Coding',\n  description = 'Ensure that all software development personnel receive training in writing secure code for their specific development environment and responsibilities.',\n  updated_at = NOW()\nWHERE id = 'c26724c4-9d1b-44fd-a40b-b4e67e80daa2';

-- Update 16.11: Leverage Vetted Modules or Services for Application Security...\nUPDATE requirements_library SET\n  title = 'Leverage Vetted Modules or Services for Application Security Components',\n  description = 'Leverage vetted modules or services for application security components, such as identity management, encryption, and auditing, instead of creating custom code for these features. Use only standardized, currently maintained, and extensively reviewed encryption algorithms.',\n  updated_at = NOW()\nWHERE id = '053f96fe-9915-4246-baec-dc82f6649d53';

-- Update 4.2: Establish and Maintain a Secure Configuration Process for Ne...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Secure Configuration Process for Network Infrastructure',\n  description = 'Establish and maintain a documented secure configuration process for network infrastructure. Review and update documentation annually, or when significant enterprise changes occur that could impact this Safeguard.',\n  updated_at = NOW()\nWHERE id = '9d12f00f-0f84-41b8-8636-59bb270d03cf';

-- Update 17.5: Assign Key Roles and Responsibilities...\nUPDATE requirements_library SET\n  title = 'Assign Key Roles and Responsibilities',\n  description = 'Assign key roles and responsibilities for incident response, including staff from legal, IT, information security, facilities, public relations, human resources, incident analysts, and investigators. Review annually, or when significant enterprise changes occur that could impact this Safeguard.',\n  updated_at = NOW()\nWHERE id = '9cd66c2e-0b29-46bb-af60-8cec03500f02';

-- Update 4.11: Enforce Remote Wipe Capability on Portable End-User Devices...\nUPDATE requirements_library SET\n  title = 'Enforce Remote Wipe Capability on Portable End-User Devices',\n  description = 'Remotely wipe enterprise data from portable end-user devices when deemed appropriate. Enterprise devices storing sensitive data, where supported, shall have remote wipe capabilities.',\n  updated_at = NOW()\nWHERE id = 'f7562b57-496d-4dbf-ab40-9ea1252d9748';