-- Update 16.3: Perform Root Cause Analysis on Security Vulnerabilities...\nUPDATE requirements_library SET\n  title = 'Perform Root Cause Analysis on Security Vulnerabilities',\n  description = 'Perform root cause analysis on security vulnerabilities. When reviewing vulnerabilities, root cause analysis determines if the vulnerability stems from enterprise software, third-party software, misconfiguration, or a combination of these sources.',\n  updated_at = NOW()\nWHERE id = 'f807ef96-2970-42ef-8a9b-9f78e90fc260';

-- Update 3.10: Encrypt Sensitive Data in Transit...\nUPDATE requirements_library SET\n  title = 'Encrypt Sensitive Data in Transit',\n  description = 'Encrypt sensitive data in transit. Example implementations can include: Transport Layer Security (TLS) and Open Secure Shell (OpenSSH).',\n  updated_at = NOW()\nWHERE id = '7af08c3a-48d2-44f2-9153-b1ac6a31d692';

-- Update 3.4: Enforce Data Retention...\nUPDATE requirements_library SET\n  title = 'Enforce Data Retention',\n  description = 'Retain data according to the enterprise''s data management process. Data retention must include both minimum and maximum timelines.',\n  updated_at = NOW()\nWHERE id = 'cd809306-0ac3-4d4f-9a2f-2ed14d8f8496';

-- Update 2.5: Use Technical Controls to Enforce Application Allowlisting...\nUPDATE requirements_library SET\n  title = 'Use Technical Controls to Enforce Application Allowlisting',\n  description = 'Use technical controls, such as application allowlisting, to prevent unauthorized software execution. Implementation: Implement application allowlisting on all enterprise assets. Configure allowlisting to permit only authorized software execution. Establish exception processes for required software. Monitor allowlisting violations.',\n  updated_at = NOW()\nWHERE id = '796d46d1-54c5-4343-99b2-eabd76f21be5';

-- Update 16.4: Establish and Manage an Inventory of Third-Party Software Co...\nUPDATE requirements_library SET\n  title = 'Establish and Manage an Inventory of Third-Party Software Components',\n  description = 'Establish and manage an inventory of the enterprise''s third-party software components. Third-party software components must be documented with title, publisher, initial install/use date, and business purpose. For enterprise software deployed to enterprise assets, update and review the inventory of third-party software components monthly, or more frequently.',\n  updated_at = NOW()\nWHERE id = '69e77584-292d-40ed-8c79-4dfc977389ae';

-- Update 3.14: Log Sensitive Data Access...\nUPDATE requirements_library SET\n  title = 'Log Sensitive Data Access',\n  description = 'Log sensitive data access, including modification and disposal.',\n  updated_at = NOW()\nWHERE id = '12404c49-afc9-441d-8730-2924f24c8558';

-- Update 6.7: Centralize Access Control...\nUPDATE requirements_library SET\n  title = 'Centralize Access Control',\n  description = 'Centralize access control for all enterprise assets through a directory service or SSO provider, where supported.',\n  updated_at = NOW()\nWHERE id = '2b34a4fe-6a16-4f2b-b8da-4a04482e46f9';

-- Update 16.5: Use Up-to-Date and Trusted Third-Party Software Components...\nUPDATE requirements_library SET\n  title = 'Use Up-to-Date and Trusted Third-Party Software Components',\n  description = 'Use up-to-date and trusted third-party software components. When possible, choose established and proven frameworks and libraries that provide adequate security. Components that are not supported with timely security updates should be replaced with alternative components.',\n  updated_at = NOW()\nWHERE id = '957167a6-0fcc-47e9-ba6e-e415e22cae6c';