-- Update 8.4: Standardize Time Synchronization...\nUPDATE requirements_library SET\n  title = 'Standardize Time Synchronization',\n  description = 'Standardize time synchronization. Configure networked and enterprise assets to implement network-based time sources. Time sources used by the enterprise shall be consistent with each other.',\n  updated_at = NOW()\nWHERE id = '81ca6ec4-1543-484d-b639-ff9a7dd7c70a';

-- Update 7.5: Perform Automated Vulnerability Scans of Internal Enterprise...\nUPDATE requirements_library SET\n  title = 'Perform Automated Vulnerability Scans of Internal Enterprise Assets',\n  description = 'Perform automated vulnerability scans of internal enterprise assets on a quarterly, or more frequent, basis. Conduct such scans from multiple vantage points.',\n  updated_at = NOW()\nWHERE id = 'eee3502a-7ec1-46bb-abe2-13519845fc9a';

-- Update 4.5: Implement and Manage a Firewall on End-User Devices...\nUPDATE requirements_library SET\n  title = 'Implement and Manage a Firewall on End-User Devices',\n  description = 'Implement and manage a host-based firewall or port-filtering tool on end-user devices, with a default-deny rule that drops all traffic except those services and ports that are explicitly allowed.',\n  updated_at = NOW()\nWHERE id = 'd31857e5-47e1-4bc4-84a2-3fac37659a56';

-- Update 4.3: Configure Automatic Session Locking on Enterprise Assets...\nUPDATE requirements_library SET\n  title = 'Configure Automatic Session Locking on Enterprise Assets',\n  description = 'Configure automatic session locking on enterprise assets after a defined period of inactivity. For general purpose operating systems, the period must not exceed 15 minutes. For mobile end-user devices, the period must not exceed 2 minutes.',\n  updated_at = NOW()\nWHERE id = 'd5abab21-62a7-4b9c-b5a6-9083b25a30fe';

-- Update 9.5: Implement DMARC...\nUPDATE requirements_library SET\n  title = 'Implement DMARC',\n  description = 'To lower the chance of spoofed or modified emails from valid domains, implement DMARC policy and verification, starting with implementing the Sender Policy Framework (SPF) and the DomainKeys Identified Mail (DKIM) standards.',\n  updated_at = NOW()\nWHERE id = 'fafd68d9-072d-493e-bf76-e5dd7141840c';

-- Update 17.4: Establish and Maintain an Incident Response Process...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain an Incident Response Process',\n  description = 'Establish and maintain an incident response process that addresses roles, responsibilities, and phases of incident response. Review annually, or when significant enterprise changes occur that could impact this Safeguard.',\n  updated_at = NOW()\nWHERE id = 'b4c79092-3857-4760-8f6d-1911c7ea3469';

-- Update 17.6: Define Mechanisms for Communicating During Incident Response...\nUPDATE requirements_library SET\n  title = 'Define Mechanisms for Communicating During Incident Response',\n  description = 'Define mechanisms for communicating during incident response. Mechanisms may include phone calls, emails, or letters. Ensure that contact information is up-to-date and that personnel know how to use communication mechanisms securely.',\n  updated_at = NOW()\nWHERE id = '163c8299-df77-4e46-874b-96007af7007c';

-- Update 9.3: Maintain and Enforce Network-Based URL Filters...\nUPDATE requirements_library SET\n  title = 'Maintain and Enforce Network-Based URL Filters',\n  description = 'Enforce and update network-based URL filters to limit an enterprise asset from connecting to potentially malicious or inappropriate websites. Example implementations include category-based filtering, reputation-based filtering, or through the use of block lists. Web filtering shall be enforced on all enterprise assets.',\n  updated_at = NOW()\nWHERE id = '0ea7df98-eef4-49bb-ab9e-235aaca97213';