-- Update 8.3: Ensure Adequate Audit Log Storage...\nUPDATE requirements_library SET\n  title = 'Ensure Adequate Audit Log Storage',\n  description = 'Ensure that logging destinations maintain adequate storage to comply with the enterprise''s audit log management process.',\n  updated_at = NOW()\nWHERE id = '2af7b5bb-dbfd-4ed0-8b4d-e187a581c6ab';

-- Update 9.1: Ensure Use of Only Fully Supported Browsers and Email Client...\nUPDATE requirements_library SET\n  title = 'Ensure Use of Only Fully Supported Browsers and Email Clients',\n  description = 'Ensure only fully supported browsers and email clients are allowed to execute in the enterprise, only using the latest version of browsers and email clients provided by the vendor.',\n  updated_at = NOW()\nWHERE id = 'b3f7428c-abd6-4e47-97eb-78f7aa9e5118';

-- Update 8.2: Collect Audit Logs...\nUPDATE requirements_library SET\n  title = 'Collect Audit Logs',\n  description = 'Collect audit logs from enterprise assets with a logging configuration in accordance with the audit log management process.',\n  updated_at = NOW()\nWHERE id = 'd998aee3-478a-41ec-8931-53965fda97df';

-- Update 13.4: Perform Traffic Filtering Between Network Segments...\nUPDATE requirements_library SET\n  title = 'Perform Traffic Filtering Between Network Segments',\n  description = 'Perform traffic filtering between network segments, where appropriate.',\n  updated_at = NOW()\nWHERE id = '75898518-2549-40c9-baf8-df3ed7968e7b';

-- Update 14.9: Conduct Role-Specific Security Awareness and Skills Training...\nUPDATE requirements_library SET\n  title = 'Conduct Role-Specific Security Awareness and Skills Training',\n  description = 'Conduct role-specific security awareness and skills training. Training content varies based on the role for which the training is being conducted. For example, the training administered to a system administrator must be different from a standard end-user. Focus training on the specific responsibilities and risks associated with the role.',\n  updated_at = NOW()\nWHERE id = 'd66d7532-25c8-4a32-90c3-94bab5db43e7';

-- Update 12.6: Use of Secure Network Management and Communication Protocols...\nUPDATE requirements_library SET\n  title = 'Use of Secure Network Management and Communication Protocols',\n  description = 'Use secure network management and communication protocols (e.g., 802.1X, Wi-Fi Protected Access 2 (WPA2) Enterprise or Wi-Fi Protected Access 3 (WPA3)).',\n  updated_at = NOW()\nWHERE id = '97ac9322-d685-4085-8b34-d6e2a98624ed';

-- Update 12.5: Centralize Network Authentication, Authorization, and Auditi...\nUPDATE requirements_library SET\n  title = 'Centralize Network Authentication, Authorization, and Auditing (AAA)',\n  description = 'Centralize network Authentication, Authorization, and Auditing (AAA).',\n  updated_at = NOW()\nWHERE id = '4ed5851c-8099-4f23-b08f-d8434c24ebfa';

-- Update 12.7: Ensure Remote Devices Utilize a VPN and are Connecting to an...\nUPDATE requirements_library SET\n  title = 'Ensure Remote Devices Utilize a VPN and are Connecting to an Enterprise''s AAA Infrastructure',\n  description = 'Require users to authenticate to an enterprise''s AAA infrastructure to access enterprise resources on end-user devices.',\n  updated_at = NOW()\nWHERE id = '340d9465-dc30-44b6-9a78-00e772a8bf58';