-- Update 9.6: Block Unnecessary File Types...\nUPDATE requirements_library SET\n  title = 'Block Unnecessary File Types',\n  description = 'Block unnecessary file types attempting to enter the enterprise''s email gateway.',\n  updated_at = NOW()\nWHERE id = '8e1f9a68-1bdb-401a-917b-77423880a423';

-- Update 10.4: Configure Automatic Anti-Malware Scanning of Removable Media...\nUPDATE requirements_library SET\n  title = 'Configure Automatic Anti-Malware Scanning of Removable Media',\n  description = 'Configure anti-malware software to automatically scan removable media.',\n  updated_at = NOW()\nWHERE id = '6adb9d66-57be-4a46-81ff-8068d7282e88';

-- Update 12.1: Ensure Network Infrastructure is Up-to-Date...\nUPDATE requirements_library SET\n  title = 'Ensure Network Infrastructure is Up-to-Date',\n  description = 'Ensure network infrastructure is kept up-to-date. Example implementations include running the latest stable release of software and/or using currently supported network-infrastructure devices.',\n  updated_at = NOW()\nWHERE id = 'd81aaba5-574e-48fc-a6c1-edc7c9985f64';

-- Update 1.4: Use Dynamic Host Configuration Protocol (DHCP) Logging to Up...\nUPDATE requirements_library SET\n  title = 'Use Dynamic Host Configuration Protocol (DHCP) Logging to Update Enterprise Asset Inventory',\n  description = 'Use DHCP logging on all DHCP servers or Internet Protocol (IP) address management tools to update the enterprise''s asset inventory. Review and use logs to update the enterprise''s asset inventory weekly, or more frequently.',\n  updated_at = NOW()\nWHERE id = '912395df-4e98-4479-884a-fdddeef2080e';

-- Update 2.1: Establish and Maintain a Software Inventory...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Software Inventory',\n  description = 'Establish and maintain a detailed inventory of all licensed software installed on enterprise assets. The software inventory must document the title, publisher, initial install/use date, and business purpose for each entry; where appropriate, include the Uniform Resource Locator (URL), app store(s), version(s), deployment mechanism, decommission date, and number of licenses. Review and update the software inventory bi-annually, or more frequently.',\n  updated_at = NOW()\nWHERE id = '33492895-42eb-4862-839d-aca977e16388';

-- Update 1.1: Establish and Maintain Detailed Enterprise Asset Inventory...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain Detailed Enterprise Asset Inventory',\n  description = 'Establish and maintain an accurate, detailed, and up-to-date inventory of all enterprise assets with the potential to store or process data, to include: end-user devices (including portable and mobile), network devices, non-computing/IoT devices, and servers. Ensure the inventory records the network address (if static), hardware address, machine name, enterprise asset owner, department for each asset, and whether the asset has been approved to connect to the network. For mobile end-user devices, MDM type tools can support this process, where appropriate. This inventory includes assets connected to the infrastructure physically, virtually, remotely, and those within cloud environments. Additionally, it includes assets that are regularly connected to the enterprise''s network infrastructure, even if they are not under control of the enterprise. Review and update the inventory of all enterprise assets bi-annually, or more frequently.',\n  updated_at = NOW()\nWHERE id = '5f4ab4c5-7a10-47b2-a932-69511b7f5764';

-- Update 1.3: Utilize an Active Discovery Tool...\nUPDATE requirements_library SET\n  title = 'Utilize an Active Discovery Tool',\n  description = 'Utilize an active discovery tool to identify assets connected to the enterprise''s network. Configure the active discovery tool to execute daily, or more frequently.',\n  updated_at = NOW()\nWHERE id = 'fd5eef5b-830e-425e-a6b4-6973d35a1ff4';

-- Update 16.1: Establish and Maintain a Secure Application Development Proc...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Secure Application Development Process',\n  description = 'Establish and maintain a secure application development process. Implementation: Integrate security throughout the software development lifecycle (SDLC). Implement secure coding standards and practices. Establish security requirements and design reviews. Train development teams on secure development practices.',\n  updated_at = NOW()\nWHERE id = '2c34c229-2741-4625-a580-da7d9fb58c12';