-- Update 6.4: Require MFA for Remote Network Access...\nUPDATE requirements_library SET\n  title = 'Require MFA for Remote Network Access',\n  description = 'Require all users to use multi-factor authentication (MFA) for remote network access.',\n  updated_at = NOW()\nWHERE id = 'cc583e12-93d7-4aa1-99c0-2cf88b6db59d';

-- Update 12.3: Securely Manage Network Assets...\nUPDATE requirements_library SET\n  title = 'Securely Manage Network Assets',\n  description = 'Securely manage enterprise assets connected to a network (end-user devices, including portable and mobile; network devices; non-computing/IoT devices; and servers). Management includes, but is not limited to, secure use of protocols, secure credential transmission, protection of credentials, and minimizing unnecessary exposure to users.',\n  updated_at = NOW()\nWHERE id = 'd8ca7926-bd7d-4227-b436-92e79782a5e5';

-- Update 6.5: Require MFA for Administrative Access...\nUPDATE requirements_library SET\n  title = 'Require MFA for Administrative Access',\n  description = 'Require multi-factor authentication (MFA) for access to enterprise assets with administrative privileges.',\n  updated_at = NOW()\nWHERE id = 'c3b69630-a409-424e-9105-eab0763b02ca';

-- Update 6.2: Establish an Access Revoking Process...\nUPDATE requirements_library SET\n  title = 'Establish an Access Revoking Process',\n  description = 'Establish and follow a process for revoking access to enterprise assets, through disabling accounts immediately upon termination, rights revocation, or role change of a user. Disabling accounts, instead of deleting accounts, allows preservation of audit trails.',\n  updated_at = NOW()\nWHERE id = 'ca8f9b34-78d8-427b-89c1-cfb1d769e175';

-- Update 13.3: Deploy a Network Intrusion Detection System...\nUPDATE requirements_library SET\n  title = 'Deploy a Network Intrusion Detection System',\n  description = 'Deploy a Network Intrusion Detection System (NIDS) to detect and alert on network-based attacks. Example implementations include the use of a Network Intrusion Detection System (NIDS), endpoint detection and response (EDR), or network security monitoring (NSM) system.',\n  updated_at = NOW()\nWHERE id = 'dd582c2e-80ce-40c9-a504-e89b8f0110aa';

-- Update 18.1: Establish and Maintain a Penetration Testing Program...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Penetration Testing Program',\n  description = 'Establish and maintain a penetration testing program. Implementation: Develop comprehensive penetration testing program and procedures. Define testing scope, frequency, and methodology. Establish penetration testing team or external provider relationships. Document penetration testing standards and requirements.',\n  updated_at = NOW()\nWHERE id = '0d856b59-617e-4103-9991-02578d1e4ed4';

-- Update 12.4: Establish and Maintain Dedicated Computing Resources for All...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain Dedicated Computing Resources for All Administrative Work',\n  description = 'Establish and maintain dedicated computing resources, either physically or logically separated, for all administrative tasks or tasks requiring administrative access. The computing resources should be segmented from the enterprise''s primary network and not be allowed Internet access.',\n  updated_at = NOW()\nWHERE id = '0930dd9c-7cab-4159-bfe7-39e7b5e41131';

-- Update 18.2: Perform Periodic External Penetration Tests...\nUPDATE requirements_library SET\n  title = 'Perform Periodic External Penetration Tests',\n  description = 'Perform periodic external penetration tests based on program requirements, no less than annually. External penetration testing must include enterprise and environmental reconnaissance to gather information that an attacker would use. Also, testing must include threat identification and, at a minimum, network, web application, and social engineering testing.',\n  updated_at = NOW()\nWHERE id = '17d993e1-b993-41a2-b68c-c7d1bdbe5919';