-- Update 13.7: Deploy a Network Intrusion Prevention System...\nUPDATE requirements_library SET\n  title = 'Deploy a Network Intrusion Prevention System',\n  description = 'Deploy a Network Intrusion Prevention System (NIPS) to block malicious network traffic.',\n  updated_at = NOW()\nWHERE id = '88d43f87-88dd-4cbd-82a5-ab7da757aaf1';

-- Update 12.7: Ensure Remote Devices Utilize a VPN and are Connecting to an...\nUPDATE requirements_library SET\n  title = 'Ensure Remote Devices Utilize a VPN and are Connecting to an Enterprise''s AAA Infrastructure',\n  description = 'Require users to authenticate to an enterprise''s AAA infrastructure to access enterprise resources on end-user devices.',\n  updated_at = NOW()\nWHERE id = '5303f863-1ee1-4721-9229-b0c608e52521';

-- Update 13.8: Deploy NetFlow Collection on Networking Boundary Devices...\nUPDATE requirements_library SET\n  title = 'Deploy NetFlow Collection on Networking Boundary Devices',\n  description = 'Enable command-line audit logging for command shells, such as Bash and PowerShell, and correlate that data with other sources of security events to identify potential threats and indicators of compromise.',\n  updated_at = NOW()\nWHERE id = 'e2b16658-fc00-4a26-bdc5-b364682a4666';

-- Update 13.9: Deploy Port-Level Access Control...\nUPDATE requirements_library SET\n  title = 'Deploy Port-Level Access Control',\n  description = 'Deploy port-level access control. Port-level access control utilizes 802.1X, or similar network access control protocols, such as certificates, and may incorporate user and/or device authentication.',\n  updated_at = NOW()\nWHERE id = '43c9e5d6-7bb7-4bb4-8a12-13374765db33';

-- Update 14.9: Conduct Role-Specific Security Awareness and Skills Training...\nUPDATE requirements_library SET\n  title = 'Conduct Role-Specific Security Awareness and Skills Training',\n  description = 'Conduct role-specific security awareness and skills training. Training content varies based on the role for which the training is being conducted. For example, the training administered to a system administrator must be different from a standard end-user. Focus training on the specific responsibilities and risks associated with the role.',\n  updated_at = NOW()\nWHERE id = '085f26e1-b28a-4afb-892a-9aa4c1086b70';

-- Update 11.1: Establish and Maintain a Data Recovery Process...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Data Recovery Process',\n  description = 'Establish and maintain a data recovery process. In the process, address the scope of data recovery activities, recovery prioritization, and the roles and responsibilities of designated personnel. Review and update documentation annually, or when significant enterprise changes occur that could impact this Safeguard.',\n  updated_at = NOW()\nWHERE id = '167ed8e3-fd73-49fb-a831-5a0c74e545a9';

-- Update 11.4: Establish and Maintain an Isolated Instance of Recovery Data...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain an Isolated Instance of Recovery Data',\n  description = 'Establish and maintain an isolated instance of recovery data. Example implementations include, version controlling backup destinations through offline, cloud, or off-site systems or services.',\n  updated_at = NOW()\nWHERE id = '4f3baf88-c6d9-429a-9d01-6686dacb1268';

-- Update 11.2: Perform Automated Backups...\nUPDATE requirements_library SET\n  title = 'Perform Automated Backups',\n  description = 'Perform automated backups of in-scope enterprise assets. Run backups weekly, or more frequently, using an automated process.',\n  updated_at = NOW()\nWHERE id = '4c72a298-bbe0-4fed-9820-3918ebe8853a';