-- Update 15.1: Establish and Maintain an Inventory of Service Providers...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain an Inventory of Service Providers',\n  description = 'Establish and maintain an inventory of authorized service providers. The inventory is to list all approved service providers, vendor type, date of vendor approval, nature of services provided, and approved by authority. Review and update the inventory annually, or when significant enterprise changes occur that could impact this Safeguard.',\n  updated_at = NOW()\nWHERE id = '68f90a71-6477-4d8e-ba69-d8ab44963b13';

-- Update 16.1: Establish and Maintain a Secure Application Development Proc...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Secure Application Development Process',\n  description = 'Establish and maintain a secure application development process. In the process, address such items as: secure application design standards, secure coding practices, developer training requirements, application security testing requirements, application security testing requirement types and frequency, application security testing requirements for third-party components, secure application deployment standards, and application security testing requirements for updates. Review and update documentation annually, or when significant enterprise changes occur that could impact this Safeguard.',\n  updated_at = NOW()\nWHERE id = '0a3953f6-5d08-4836-a050-be72b4cde5c9';

-- Update 17.1: Designate Personnel to Manage Incident Handling...\nUPDATE requirements_library SET\n  title = 'Designate Personnel to Manage Incident Handling',\n  description = 'Designate one key person, and at least one backup, who will manage the enterprise''s incident handling process. Management personnel are responsible for the coordination and documentation of incident response and recovery efforts and can consist of employees internal to the enterprise, service providers, or a hybrid approach. If using a service provider, designate at least one person internal to the enterprise to oversee any third-party work. Review annually, or when significant enterprise changes occur that could impact this Safeguard.',\n  updated_at = NOW()\nWHERE id = '481bb1db-8651-4b97-a89c-0f83db14c2f4';

-- Update 17.2: Establish and Maintain Contact Information for Reporting Sec...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain Contact Information for Reporting Security Incidents',\n  description = 'Establish and maintain contact information for parties that need to be informed of security incidents. Contacts may include internal staff, service providers, law enforcement, cyber insurance providers, relevant government agencies, Information Sharing and Analysis Center (ISAC) partners, or other stakeholders. Verify contacts annually to ensure that information is up-to-date.',\n  updated_at = NOW()\nWHERE id = '027e8bad-10bb-4859-b990-1f5abd5d5b01';

-- Update 17.3: Establish and Maintain an Enterprise Process for Reporting I...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain an Enterprise Process for Reporting Incidents',\n  description = 'Establish and maintain a documented enterprise process for the workforce to report security incidents. The process includes reporting timeframe, personnel to report to, mechanism for reporting, and the minimum information to be reported. Ensure the process is publicly available to all of the workforce. Review annually, or when significant enterprise changes occur that could impact this Safeguard.',\n  updated_at = NOW()\nWHERE id = '51cdded3-af0d-48a3-9ea6-3b59891a2cf6';

-- Update 15.2: Establish and Maintain a Service Provider Management Policy...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Service Provider Management Policy',\n  description = 'Establish and maintain a policy for managing service providers that includes a risk assessment, business purpose and mission alignment, contractual requirements for security, privacy expectations, and remediation processes. The policy shall mandate minimum security requirements for all service providers. Review and update the policy annually, or when significant enterprise changes occur.',\n  updated_at = NOW()\nWHERE id = '4c29e3d7-1316-42ac-a2e7-2df6cb5c7dc8';

-- Update 9.2: Use DNS Filtering Services...\nUPDATE requirements_library SET\n  title = 'Use DNS Filtering Services',\n  description = 'Use DNS filtering services to help block access to known malicious domains.',\n  updated_at = NOW()\nWHERE id = 'd49c98ac-ec28-43ba-904d-2e5c1695da31';

-- Update 15.3: Classify Service Providers...\nUPDATE requirements_library SET\n  title = 'Classify Service Providers',\n  description = 'Classify service providers. Sensitivity levels are determined based on access to sensitive data, administrative privileges, and ability to disrupt business operations. Use this classification to inform whether enhanced requirements are needed based on risk.',\n  updated_at = NOW()\nWHERE id = '52145d67-e92b-4918-9ff9-e25f36bd686d';