-- Update 8.9: Centralize Audit Logs...\nUPDATE requirements_library SET\n  title = 'Centralize Audit Logs',\n  description = 'Centralize, to the extent possible, audit log collection and retention across enterprise assets.',\n  updated_at = NOW()\nWHERE id = '67bef15e-79ec-46c6-8c5d-589ee72a95e6';

-- Update 14.3: Train Workforce Members on Authentication Best Practices...\nUPDATE requirements_library SET\n  title = 'Train Workforce Members on Authentication Best Practices',\n  description = 'Train workforce members on authentication best practices. Example topics include creating secure passwords, password managers, MFA, and phishing-resistant MFA.',\n  updated_at = NOW()\nWHERE id = 'c56ae651-5afc-40a6-a4aa-77221616cbc7';

-- Update 5.1: Establish and Maintain an Inventory of Accounts...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain an Inventory of Accounts',\n  description = 'Establish and maintain an inventory of all accounts managed in the enterprise. The inventory shall include both user and administrator accounts. The inventory shall include the person or entity the account belongs to, the systems it applies to, and an active or inactive status. Review the inventory quarterly, or more frequently.',\n  updated_at = NOW()\nWHERE id = '9cb28c82-61d2-40c3-a61f-04da59acf3fd';

-- Update 5.3: Disable Dormant Accounts...\nUPDATE requirements_library SET\n  title = 'Disable Dormant Accounts',\n  description = 'Delete or disable any dormant accounts after a period of 45 days of inactivity, where supported.',\n  updated_at = NOW()\nWHERE id = '669c1e60-cb45-4133-86cc-6c37591fe475';

-- Update 5.4: Restrict Administrator Privileges to Dedicated Administrator...\nUPDATE requirements_library SET\n  title = 'Restrict Administrator Privileges to Dedicated Administrator Accounts',\n  description = 'Restrict administrator privileges to dedicated administrator accounts on enterprise assets. Conduct general computing activities, such as internet browsing, email, and productivity suite use, from the user''s standard account.',\n  updated_at = NOW()\nWHERE id = '7d27742e-7fd6-47e9-9208-114905e1a932';

-- Update 6.1: Establish an Access Granting Process...\nUPDATE requirements_library SET\n  title = 'Establish an Access Granting Process',\n  description = 'Establish and follow a process for granting access to enterprise assets upon new hire, promotion, or role change of a user.',\n  updated_at = NOW()\nWHERE id = '7d9a2680-0323-45cb-847c-45f608ab12df';

-- Update 14.4: Train Workforce on Data Handling Best Practices...\nUPDATE requirements_library SET\n  title = 'Train Workforce on Data Handling Best Practices',\n  description = 'Train workforce members on data handling best practices. Example topics include appropriate use, handling requirements, acceptable locations for storage, encryption, and destruction.',\n  updated_at = NOW()\nWHERE id = '7ae4c58b-0ed2-41cd-86c5-c84b6cd7a6f1';

-- Update 7.1: Establish and Maintain a Vulnerability Management Process...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Vulnerability Management Process',\n  description = 'Establish and maintain a documented vulnerability management process for enterprise assets. Review and update documentation annually, or when significant enterprise changes occur that could impact this Safeguard.',\n  updated_at = NOW()\nWHERE id = '2b1471e8-a473-4f44-ba63-be1d5098aa9e';