-- Update 5.7: Threat intelligence...\nUPDATE requirements_library SET\n  title = 'Threat intelligence',\n  description = 'Information relating to information security threats shall be collected and analyzed to produce threat intelligence.',\n  updated_at = NOW()\nWHERE id = 'd7a933c7-07ad-40b1-b222-6bbf2a2ddd88';

-- Update 5.8: Information security in project management...\nUPDATE requirements_library SET\n  title = 'Information security in project management',\n  description = 'Information security shall be integrated into project management.',\n  updated_at = NOW()\nWHERE id = 'ec3b58c0-20c9-4068-8e60-af0ce816d2d6';

-- Update 5.9: Inventory of information and other associated assets...\nUPDATE requirements_library SET\n  title = 'Inventory of information and other associated assets',\n  description = 'An inventory of information and other associated assets, including owners, shall be developed and maintained.',\n  updated_at = NOW()\nWHERE id = '0b562b17-0e2e-4bf4-8cb7-46e4f9e43dbd';

-- Update 5.4: Restrict Administrator Privileges to Dedicated Administrator...\nUPDATE requirements_library SET\n  title = 'Restrict Administrator Privileges to Dedicated Administrator Accounts',\n  description = 'Restrict administrator privileges to dedicated administrator accounts on enterprise assets. Conduct general computing activities, such as internet browsing, email, and productivity suite use, from the user''s standard account.',\n  updated_at = NOW()\nWHERE id = 'd1308cdc-6f09-4bb5-b4d3-66c518e9a63c';

-- Update 5.5: Establish and Maintain an Inventory of Service Accounts...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain an Inventory of Service Accounts',\n  description = 'Establish and maintain an inventory of service accounts. The inventory shall include, but is not limited to, purpose, ownership, and authorized users of the account. Perform service account reviews to validate that all service accounts are authorized, warranted, and privileged are still required, on a recurring schedule at a minimum annually, or more frequently.',\n  updated_at = NOW()\nWHERE id = '80421d9a-3fcc-4686-bbbd-1dccd7ab1d73';

-- Update 18.1: Establish and Maintain a Penetration Testing Program...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Penetration Testing Program',\n  description = 'Establish and maintain a penetration testing program appropriate to the size, complexity, and maturity of the enterprise. Penetration testing program characteristics include scope, such as network, web application, Application Programming Interface (API), hosted services, and physical premise controls; frequency; limitations, such as acceptable hours, and excluded attack types; point of contact information; remediation, such as how findings will be routed internally; and retrospective requirements.',\n  updated_at = NOW()\nWHERE id = '26672f0c-b50b-41cc-8dd9-647652380bc7';

-- Update 14.2: Train Workforce Members to Recognize Social Engineering Atta...\nUPDATE requirements_library SET\n  title = 'Train Workforce Members to Recognize Social Engineering Attacks',\n  description = 'Train workforce members to recognize social engineering attacks, such as phishing, pretexting, and tailgating.',\n  updated_at = NOW()\nWHERE id = 'cbd556ba-39b5-4de0-9ce4-cd7aa220a988';

-- Update 5.1: Establish and Maintain an Inventory of Accounts...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain an Inventory of Accounts',\n  description = 'Establish and maintain an inventory of all accounts managed in the enterprise. The inventory shall include both user and administrator accounts. The inventory shall include the person or entity the account belongs to, the systems it applies to, and an active or inactive status. Review the inventory quarterly, or more frequently.',\n  updated_at = NOW()\nWHERE id = '3fcd032b-7c17-4d13-8145-2bf8d3eb990d';