-- Update 10.5: Enable Anti-Exploitation Features...\nUPDATE requirements_library SET\n  title = 'Enable Anti-Exploitation Features',\n  description = 'Enable anti-exploitation features on enterprise assets and software, where possible, such as Microsoft® Data Execution Prevention (DEP), Windows® Defender Exploit Guard (WDEG), or Apple® System Integrity Protection (SIP) and Gatekeeper™.',\n  updated_at = NOW()\nWHERE id = '9b471941-ec44-416a-981a-d962a8551029';

-- Update 13.3: Deploy a Network Intrusion Detection System...\nUPDATE requirements_library SET\n  title = 'Deploy a Network Intrusion Detection System',\n  description = 'Deploy a Network Intrusion Detection System (NIDS) to detect and alert on network-based attacks. Example implementations include the use of a Network Intrusion Detection System (NIDS), endpoint detection and response (EDR), or network security monitoring (NSM) system.',\n  updated_at = NOW()\nWHERE id = 'c8eee43c-e739-4390-a2d0-4b00333b4ba0';

-- Update 17.3: Establish and Maintain an Enterprise Process for Reporting I...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain an Enterprise Process for Reporting Incidents',\n  description = 'Establish and maintain an enterprise process for the workforce to report suspected cybersecurity incidents. The process includes reporting timeframe, personnel to report to, mechanism for reporting, and the minimum information to be reported. Ensure the workforce is trained on the process and equipped with the necessary information to report incidents. Review annually, or when significant enterprise changes occur that could impact this Safeguard.',\n  updated_at = NOW()\nWHERE id = 'bef04421-0ff5-436a-8827-bf35d88146be';

-- Update 12.3: Securely Manage Network Assets...\nUPDATE requirements_library SET\n  title = 'Securely Manage Network Assets',\n  description = 'Securely manage enterprise assets connected to a network (end-user devices, including portable and mobile; network devices; non-computing/IoT devices; and servers). Management includes, but is not limited to, secure use of protocols, secure credential transmission, protection of credentials, and minimizing unnecessary exposure to users.',\n  updated_at = NOW()\nWHERE id = '89f985ac-fee4-4f24-b377-6f7526d1d1d2';

-- Update 12.4: Establish and Maintain Dedicated Computing Resources for All...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain Dedicated Computing Resources for All Administrative Work',\n  description = 'Establish and maintain dedicated computing resources, either physically or logically separated, for all administrative tasks or tasks requiring administrative access. The computing resources should be segmented from the enterprise''s primary network and not be allowed Internet access.',\n  updated_at = NOW()\nWHERE id = 'd4bca65e-37ce-43fa-a52c-58dffb6d4fb7';

-- Update 6.2: Establish an Access Revoking Process...\nUPDATE requirements_library SET\n  title = 'Establish an Access Revoking Process',\n  description = 'Establish and follow a process for revoking access to enterprise assets, through disabling accounts immediately upon termination, rights revocation, or role change of a user. Disabling accounts, instead of deleting accounts, allows preservation of audit trails.',\n  updated_at = NOW()\nWHERE id = 'f04d7aad-29ec-4dbe-b6ac-87d368b40562';

-- Update 18.3: Remedy Penetration Test Findings...\nUPDATE requirements_library SET\n  title = 'Remedy Penetration Test Findings',\n  description = 'Remediate penetration test findings based on the enterprise''s policy for remediation scope and prioritization.',\n  updated_at = NOW()\nWHERE id = '9df88578-1c69-4d43-97a9-47bcf43f126b';

-- Update 6.6: Establish and Maintain an Inventory of Authentication and Au...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain an Inventory of Authentication and Authorization Systems',\n  description = 'Establish and maintain an inventory of the enterprise''s authentication and authorization systems, whether on-premises or hosted externally. Example systems include single sign-on, directory services, domain controllers, certificate authorities, privileged access management, federation, and others. The inventory shall include system owner and system administrator (internal or external).',\n  updated_at = NOW()\nWHERE id = 'ae7b3148-47c5-4387-8426-e8b4e632b291';