-- Update 3.4: Enforce Data Retention...\nUPDATE requirements_library SET\n  title = 'Enforce Data Retention',\n  description = 'Retain data according to the enterprise''s data management process. Data retention must include both minimum and maximum timelines.',\n  updated_at = NOW()\nWHERE id = '533989be-821d-4156-808f-b6c1069a00ac';

-- Update 3.5: Securely Dispose of Data...\nUPDATE requirements_library SET\n  title = 'Securely Dispose of Data',\n  description = 'Securely dispose of data as outlined in the enterprise''s data management process. Ensure the disposal process and method are commensurate with the data sensitivity.',\n  updated_at = NOW()\nWHERE id = '30ae5396-4932-4764-8741-8950ef217bcf';

-- Update 4.2: Establish and Maintain a Secure Configuration Process for Ne...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Secure Configuration Process for Network Infrastructure',\n  description = 'Establish and maintain a documented secure configuration process for network infrastructure. Review and update documentation annually, or when significant enterprise changes occur that could impact this Safeguard.',\n  updated_at = NOW()\nWHERE id = '381ee456-ce6d-4b5e-80cb-fd59e2e7f39e';

-- Update 4.3: Configure Automatic Session Locking on Enterprise Assets...\nUPDATE requirements_library SET\n  title = 'Configure Automatic Session Locking on Enterprise Assets',\n  description = 'Configure automatic session locking on enterprise assets after a defined period of inactivity. For general purpose operating systems, the period must not exceed 15 minutes. For mobile end-user devices, the period must not exceed 2 minutes.',\n  updated_at = NOW()\nWHERE id = 'f8077674-a842-4d91-b5d4-ab8157cdb3ad';

-- Update 5.4: Restrict Administrator Privileges to Dedicated Administrator...\nUPDATE requirements_library SET\n  title = 'Restrict Administrator Privileges to Dedicated Administrator Accounts',\n  description = 'Restrict administrator privileges to dedicated administrator accounts on enterprise assets. Conduct general computing activities, such as internet browsing, email, and productivity suite use, from the user''s standard account.',\n  updated_at = NOW()\nWHERE id = 'c4dee013-cbcd-48ca-a27c-7ab2fb1531e1';

-- Update 6.5: Require MFA for Administrative Access...\nUPDATE requirements_library SET\n  title = 'Require MFA for Administrative Access',\n  description = 'Require multi-factor authentication (MFA) for access to enterprise assets with administrative privileges.',\n  updated_at = NOW()\nWHERE id = 'ad1b1fca-64c5-4379-bc54-05f039ee8eed';

-- Update 7.1: Establish and Maintain a Vulnerability Management Process...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Vulnerability Management Process',\n  description = 'Establish and maintain a documented vulnerability management process for enterprise assets. Review and update documentation annually, or when significant enterprise changes occur that could impact this Safeguard.',\n  updated_at = NOW()\nWHERE id = 'd7ba26b3-9567-45a4-934b-81b4393424f4';

-- Update 7.4: Perform Automated Application Patch Management...\nUPDATE requirements_library SET\n  title = 'Perform Automated Application Patch Management',\n  description = 'Perform application updates on enterprise assets through automated patch management on a monthly, or more frequent, basis.',\n  updated_at = NOW()\nWHERE id = '3ef71175-eaa0-4a90-a489-be0a3bb83b3e';