-- Update 17.1: Establish and Maintain an Incident Response Process...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain an Incident Response Process',\n  description = 'Designate personnel to manage incident handling. Implementation: Assign dedicated personnel to manage security incidents. Establish incident response team structure and responsibilities. Define roles for incident detection, analysis, containment, and recovery. Provide incident response training to designated personnel.',\n  updated_at = NOW()\nWHERE id = '0ae5ac28-a96b-4568-9ea4-1ef4ca97f8ea';

-- Update 4.5: Implement and Manage a Firewall on End-User Devices...\nUPDATE requirements_library SET\n  title = 'Implement and Manage a Firewall on End-User Devices',\n  description = 'Implement and manage a host-based firewall or port-filtering tool on end-user devices, with a default-deny rule that drops all traffic except those services and ports that are explicitly allowed.',\n  updated_at = NOW()\nWHERE id = '996dc857-3d50-4928-b5d1-55367861a3df';

-- Update 4.3: Configure Automatic Session Locking on Enterprise Assets...\nUPDATE requirements_library SET\n  title = 'Configure Automatic Session Locking on Enterprise Assets',\n  description = 'Configure automatic session locking on enterprise assets after a defined period of inactivity. For general purpose operating systems, the period must not exceed 15 minutes. For mobile end-user devices, the period must not exceed 2 minutes.',\n  updated_at = NOW()\nWHERE id = '6d327a24-8ec1-4b98-9cc1-7acc10ea4cc4';

-- Update 5.5: Establish and Maintain an Inventory of Service Accounts...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain an Inventory of Service Accounts',\n  description = 'Establish and maintain an inventory of service accounts. The inventory shall include, but is not limited to, purpose, ownership, and authorized users of the account. Perform service account reviews to validate that all service accounts are authorized, warranted, and privileged are still required, on a recurring schedule at a minimum annually, or more frequently.',\n  updated_at = NOW()\nWHERE id = 'aff3d838-2b01-4a0d-9c3c-20d5ebd406b5';

-- Update 9.5: Implement DMARC...\nUPDATE requirements_library SET\n  title = 'Implement DMARC',\n  description = 'To lower the chance of spoofed or modified emails from valid domains, implement DMARC policy and verification, starting with implementing the Sender Policy Framework (SPF) and the DomainKeys Identified Mail (DKIM) standards.',\n  updated_at = NOW()\nWHERE id = '59ba1a4a-7a65-420f-b912-88844609d9dc';

-- Update 10.7: Use Behavior-Based Anti-Malware Software...\nUPDATE requirements_library SET\n  title = 'Use Behavior-Based Anti-Malware Software',\n  description = 'Use behavior-based anti-malware software.',\n  updated_at = NOW()\nWHERE id = '000caae9-9225-4a4c-8a39-46b3c9686c30';

-- Update 6.6: Establish and Maintain an Inventory of Authentication and Au...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain an Inventory of Authentication and Authorization Systems',\n  description = 'Establish and maintain an inventory of the enterprise''s authentication and authorization systems, whether on-premises or hosted externally. Example systems include single sign-on, directory services, domain controllers, certificate authorities, privileged access management, federation, and others. The inventory shall include system owner and system administrator (internal or external).',\n  updated_at = NOW()\nWHERE id = 'b66d5cef-74e9-447b-a511-2aa2b33513aa';

-- Update 6.3: Require MFA for Externally-Exposed Applications...\nUPDATE requirements_library SET\n  title = 'Require MFA for Externally-Exposed Applications',\n  description = 'Require all users to use multi-factor authentication (MFA) for externally-exposed enterprise or third-party applications.',\n  updated_at = NOW()\nWHERE id = 'ce11b7bc-9d89-4c46-8dac-575464669908';