-- Update 5.2: Use Unique Passwords...\nUPDATE requirements_library SET\n  title = 'Use Unique Passwords',\n  description = 'Use unique passwords for all enterprise assets. Best practice implementation includes, at a minimum, an 8-character password for accounts using MFA and a 14-character password for accounts not using MFA.',\n  updated_at = NOW()\nWHERE id = '8c7a12c6-cb48-4021-90fc-817983cb3d63';

-- Update 9.3: Maintain and Enforce Network-Based URL Filters...\nUPDATE requirements_library SET\n  title = 'Maintain and Enforce Network-Based URL Filters',\n  description = 'Enforce and update network-based URL filters to limit an enterprise asset from connecting to potentially malicious or inappropriate websites. Example implementations include category-based filtering, reputation-based filtering, or through the use of block lists. Web filtering shall be enforced on all enterprise assets.',\n  updated_at = NOW()\nWHERE id = 'd9ab9dfc-2be5-403e-adfb-4dd04c3fd9b0';

-- Update 5.3: Disable Dormant Accounts...\nUPDATE requirements_library SET\n  title = 'Disable Dormant Accounts',\n  description = 'Delete or disable any dormant accounts after a period of 45 days of inactivity, where supported.',\n  updated_at = NOW()\nWHERE id = 'b1c5da67-d1fe-4d8b-8798-4a9a2d62145a';

-- Update 6.2: Establish an Access Revoking Process...\nUPDATE requirements_library SET\n  title = 'Establish an Access Revoking Process',\n  description = 'Establish and follow a process for revoking access to enterprise assets, through disabling accounts immediately upon termination, rights revocation, or role change of a user. Disabling accounts, instead of deleting accounts, allows preservation of audit trails.',\n  updated_at = NOW()\nWHERE id = '67208aba-505a-4b55-bbe1-04954c1f0236';

-- Update 9.2: Use DNS Filtering Services...\nUPDATE requirements_library SET\n  title = 'Use DNS Filtering Services',\n  description = 'Use DNS filtering services to help block access to known malicious domains.',\n  updated_at = NOW()\nWHERE id = '75da41e7-dd75-4c7b-bf1d-3b80a2ef0b48';

-- Update 10.1: Deploy and Maintain Anti-Malware Software...\nUPDATE requirements_library SET\n  title = 'Deploy and Maintain Anti-Malware Software',\n  description = 'Deploy and maintain anti-malware software on all enterprise assets.',\n  updated_at = NOW()\nWHERE id = '9db478dc-b827-41d9-a1bb-86412680d924';

-- Update 10.2: Configure Automatic Anti-Malware Signature Updates...\nUPDATE requirements_library SET\n  title = 'Configure Automatic Anti-Malware Signature Updates',\n  description = 'Configure automatic anti-malware signature updates on all enterprise assets.',\n  updated_at = NOW()\nWHERE id = '8aef80d3-f5d8-41c8-837c-5d874b27bedb';

-- Update 7.1: Establish and Maintain a Vulnerability Management Process...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Vulnerability Management Process',\n  description = 'Establish and maintain a documented vulnerability management process for enterprise assets. Review and update documentation annually, or when significant enterprise changes occur that could impact this Safeguard.',\n  updated_at = NOW()\nWHERE id = '21849826-f9c4-4ab0-9846-62d9c8496767';