-- Update 9.2: Use DNS Filtering Services...\nUPDATE requirements_library SET\n  title = 'Use DNS Filtering Services',\n  description = 'Use DNS filtering services to help block access to known malicious domains.',\n  updated_at = NOW()\nWHERE id = '4fa6bfd0-2d39-460c-8ea1-4a7680ecbb9c';

-- Update 2.2: Ensure Authorized Software is Currently Supported...\nUPDATE requirements_library SET\n  title = 'Ensure Authorized Software is Currently Supported',\n  description = 'Ensure that only currently supported software is designated as authorized in the software inventory for enterprise assets. If software is unsupported, yet necessary for the fulfillment of the enterprise''s mission, document an exception detailing mitigating controls and residual risk acceptance. For any unsupported software without an exception documentation, designate as unauthorized. Review the software list to verify software support at least monthly, or more frequently.',\n  updated_at = NOW()\nWHERE id = '381a053f-4c96-4d97-a129-bed806232337';

-- Update 9.4: Restrict Unnecessary or Unauthorized Browser and Email Clien...\nUPDATE requirements_library SET\n  title = 'Restrict Unnecessary or Unauthorized Browser and Email Client Extensions',\n  description = 'Restrict unnecessary or unauthorized browser and email client extensions, including add-ons, and plug-ins.',\n  updated_at = NOW()\nWHERE id = '564aed9a-19e5-4daf-bc60-4e19fe7838f1';

-- Update 2.3: Address Unauthorized Software...\nUPDATE requirements_library SET\n  title = 'Address Unauthorized Software',\n  description = 'Ensure that unauthorized software is either removed from use on enterprise assets or receives a documented exception. Review monthly, or more frequently.',\n  updated_at = NOW()\nWHERE id = 'a6d6d02a-41ca-4252-b642-a05f0dca1911';

-- Update 3.5: Securely Dispose of Data...\nUPDATE requirements_library SET\n  title = 'Securely Dispose of Data',\n  description = 'Securely dispose of data as outlined in the enterprise''s data management process. Ensure the disposal process and method are commensurate with the data sensitivity.',\n  updated_at = NOW()\nWHERE id = 'e26cdc5f-7b64-4175-b5b9-02a1c0f13d96';

-- Update 3.6: Encrypt Data on End-User Devices...\nUPDATE requirements_library SET\n  title = 'Encrypt Data on End-User Devices',\n  description = 'Encrypt data on end-user devices containing sensitive data. Example implementations can include: Windows BitLocker®, Apple FileVault®, Linux dm-crypt.',\n  updated_at = NOW()\nWHERE id = 'db5b26f9-e2e3-40af-8e7d-149796b4c694';

-- Update 15.3: Classify Service Providers...\nUPDATE requirements_library SET\n  title = 'Classify Service Providers',\n  description = 'Classify service providers. Sensitivity levels are determined based on access to sensitive data, administrative privileges, and ability to disrupt business operations. Use this classification to inform whether enhanced requirements are needed based on risk.',\n  updated_at = NOW()\nWHERE id = '0d95e0d0-1b5a-4bd6-8a4b-99757cab8d25';

-- Update 5.2: Use Unique Passwords...\nUPDATE requirements_library SET\n  title = 'Use Unique Passwords',\n  description = 'Use unique passwords for all enterprise assets. Best practice implementation includes, at a minimum, an 8-character password for accounts using MFA and a 14-character password for accounts not using MFA.',\n  updated_at = NOW()\nWHERE id = '6febb0cf-646e-470d-bd78-0d564d188e03';