-- Update 6.6: Establish and Maintain an Inventory of Authentication and Au...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain an Inventory of Authentication and Authorization Systems',\n  description = 'Establish and maintain an inventory of the enterprise''s authentication and authorization systems, whether on-premises or hosted externally. Example systems include single sign-on, directory services, domain controllers, certificate authorities, privileged access management, federation, and others. The inventory shall include system owner and system administrator (internal or external).',\n  updated_at = NOW()\nWHERE id = '7e49185a-716c-4e09-883e-b8772bd4edd7';

-- Update 7.3: Perform Automated Operating System Patch Management...\nUPDATE requirements_library SET\n  title = 'Perform Automated Operating System Patch Management',\n  description = 'Perform operating system updates on enterprise assets through automated patch management on a monthly, or more frequent, basis.',\n  updated_at = NOW()\nWHERE id = '45603e20-d2e9-4956-b59c-d00507d17bea';

-- Update 7.4: Perform Automated Application Patch Management...\nUPDATE requirements_library SET\n  title = 'Perform Automated Application Patch Management',\n  description = 'Perform application updates on enterprise assets through automated patch management on a monthly, or more frequent, basis.',\n  updated_at = NOW()\nWHERE id = '2be7aebf-f277-468f-bb80-df62af51900c';

-- Update 7.8: Equipment siting and protection...\nUPDATE requirements_library SET\n  title = 'Equipment siting and protection',\n  description = 'Equipment shall be sited securely and protected.',\n  updated_at = NOW()\nWHERE id = '6c3dba48-fcfa-41ab-96e0-1e18150f83b5';

-- Update 6.2: Establish an Access Revoking Process...\nUPDATE requirements_library SET\n  title = 'Establish an Access Revoking Process',\n  description = 'Establish and follow a process for revoking access to enterprise assets, through disabling accounts immediately upon termination, rights revocation, or role change of a user. Disabling accounts, instead of deleting accounts, allows preservation of audit trails.',\n  updated_at = NOW()\nWHERE id = '8a53d53c-8230-49da-8e96-6fd5e3f11fed';

-- Update 7.10: Storage media...\nUPDATE requirements_library SET\n  title = 'Storage media',\n  description = 'Storage media shall be managed according to the classification scheme and handling requirements of the organization.',\n  updated_at = NOW()\nWHERE id = '482574a4-e869-4436-85f2-607767f0cab4';

-- Update 6.7: Centralize Access Control...\nUPDATE requirements_library SET\n  title = 'Centralize Access Control',\n  description = 'Centralize access control for all enterprise assets through a directory service or SSO provider, where supported.',\n  updated_at = NOW()\nWHERE id = '8b6c7917-9b95-42fa-a3a6-2f1d1e8a434b';

-- Update 7.11: Supporting utilities...\nUPDATE requirements_library SET\n  title = 'Supporting utilities',\n  description = 'Information processing facilities shall be protected from power failures and other disruptions caused by failures in supporting utilities.',\n  updated_at = NOW()\nWHERE id = 'e313e2d0-1ee9-4d84-be58-a4fe3ba59032';