-- Update 13.2: Deploy a Host-Based Intrusion Detection System...\nUPDATE requirements_library SET\n  title = 'Deploy a Host-Based Intrusion Detection System',\n  description = 'Deploy a Host-based Intrusion Detection System (HIDS) solution on enterprise assets, where appropriate and/or necessary.',\n  updated_at = NOW()\nWHERE id = '6465f475-677b-49ef-9b07-d944fbea4b27';

-- Update 16.1: Establish and Maintain a Secure Application Development Proc...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Secure Application Development Process',\n  description = 'Establish and maintain a secure application development process. In the process, address such items as: secure application design standards, secure coding practices, developer training requirements, application security testing requirements, application security testing requirement types and frequency, application security testing requirements for third-party components, secure application deployment standards, and application security testing requirements for updates. Review and update documentation annually, or when significant enterprise changes occur that could impact this Safeguard.',\n  updated_at = NOW()\nWHERE id = '84316f7d-e4a6-49f4-b7c6-9ca5d66c3cba';

-- Update 5.2: Use Unique Passwords...\nUPDATE requirements_library SET\n  title = 'Use Unique Passwords',\n  description = 'Use unique passwords for all enterprise assets. Best practice implementation includes, at a minimum, an 8-character password for accounts using MFA and a 14-character password for accounts not using MFA.',\n  updated_at = NOW()\nWHERE id = '75fdae5b-8cb5-4b6f-bdb7-d54ff6a3f995';

-- Update 4.1: Establish and Maintain a Secure Configuration Process...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Secure Configuration Process',\n  description = 'Establish and maintain a documented secure configuration process for enterprise assets (end-user devices, including portable and mobile, non-computing/IoT devices, and servers) and software (operating systems and applications). Review and update documentation annually, or when significant enterprise changes occur that could impact this Safeguard.',\n  updated_at = NOW()\nWHERE id = '6aef53a4-3bc6-40b9-a6a5-76593032f1d5';

-- Update 16.2: Establish and Maintain a Process to Accept and Address Softw...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Process to Accept and Address Software Vulnerabilities',\n  description = 'Establish and maintain a process to accept and address reports of software vulnerabilities, including public disclosure of enterprise software vulnerabilities. The process is to include such items as: a vulnerability disclosure policy, a method for external entities to contact the enterprise to report vulnerabilities in enterprise software, a process for assessing, prioritizing, and tracking vulnerabilities, and a process for releasing updates to address vulnerabilities.',\n  updated_at = NOW()\nWHERE id = '1c873439-3155-44a5-93f0-98208409c0af';

-- Update 16.3: Perform Root Cause Analysis on Security Vulnerabilities...\nUPDATE requirements_library SET\n  title = 'Perform Root Cause Analysis on Security Vulnerabilities',\n  description = 'Perform root cause analysis on security vulnerabilities. When reviewing vulnerabilities, root cause analysis determines if the vulnerability stems from enterprise software, third-party software, misconfiguration, or a combination of these sources.',\n  updated_at = NOW()\nWHERE id = '963cfb2d-fa33-4ca5-8c33-9263d491ddae';

-- Update 1.3: Utilize an Active Discovery Tool...\nUPDATE requirements_library SET\n  title = 'Utilize an Active Discovery Tool',\n  description = 'Utilize an active discovery tool to identify assets connected to the enterprise''s network. Configure the active discovery tool to execute daily, or more frequently.',\n  updated_at = NOW()\nWHERE id = 'cba7e2fa-98ad-4445-965e-5af282378528';

-- Update 1.5: Use a Passive Asset Discovery Tool...\nUPDATE requirements_library SET\n  title = 'Use a Passive Asset Discovery Tool',\n  description = 'Use a passive discovery tool to identify assets connected to the enterprise''s network. Review and use scans to update the enterprise''s asset inventory at least weekly, or more frequently.',\n  updated_at = NOW()\nWHERE id = '89ae06e8-31fa-4b7d-a2b6-6dc5ed0fef5a';