-- Update 8.2: Collect Audit Logs...\nUPDATE requirements_library SET\n  title = 'Collect Audit Logs',\n  description = 'Collect audit logs from enterprise assets with a logging configuration in accordance with the audit log management process.',\n  updated_at = NOW()\nWHERE id = 'a770b8f8-a082-45f1-bde1-069d2ce973af';

-- Update 9.2: Use DNS Filtering Services...\nUPDATE requirements_library SET\n  title = 'Use DNS Filtering Services',\n  description = 'Use DNS filtering services to help block access to known malicious domains.',\n  updated_at = NOW()\nWHERE id = 'dae6daec-622c-45a2-ba09-74bb98556669';

-- Update 1.2: Address Unauthorized Assets...\nUPDATE requirements_library SET\n  title = 'Address Unauthorized Assets',\n  description = 'Ensure that a process exists to address unauthorized assets on a weekly basis. The enterprise may choose to remove the asset from the network, deny the asset from connecting remotely to the network, or quarantine the asset.',\n  updated_at = NOW()\nWHERE id = '7797aac2-379f-408d-a676-4c9cd122d76b';

-- Update 3.6: Encrypt Data on End-User Devices...\nUPDATE requirements_library SET\n  title = 'Encrypt Data on End-User Devices',\n  description = 'Encrypt data on end-user devices containing sensitive data. Example implementations can include: Windows BitLocker®, Apple FileVault®, Linux dm-crypt.',\n  updated_at = NOW()\nWHERE id = '3c33020d-8b90-4e3a-9eae-b7627a8aa477';

-- Update 2.1: Establish and Maintain a Software Inventory...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Software Inventory',\n  description = 'Establish and maintain a detailed inventory of all licensed software installed on enterprise assets. The software inventory must document the title, publisher, initial install/use date, and business purpose for each entry; where appropriate, include the Uniform Resource Locator (URL), app store(s), version(s), deployment mechanism, decommission date, and number of licenses. Review and update the software inventory bi-annually, or more frequently.',\n  updated_at = NOW()\nWHERE id = '5cf8ccde-035e-45fe-8980-968af0e7f4cd';

-- Update 2.2: Ensure Authorized Software is Currently Supported...\nUPDATE requirements_library SET\n  title = 'Ensure Authorized Software is Currently Supported',\n  description = 'Ensure that only currently supported software is designated as authorized in the software inventory for enterprise assets. If software is unsupported, yet necessary for the fulfillment of the enterprise''s mission, document an exception detailing mitigating controls and residual risk acceptance. For any unsupported software without an exception documentation, designate as unauthorized. Review the software list to verify software support at least monthly, or more frequently.',\n  updated_at = NOW()\nWHERE id = '10aeb1c0-f0e9-477e-a4fe-4c489a34fc2f';

-- Update 3.1: Establish and Maintain a Data Management Process...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Data Management Process',\n  description = 'Establish and maintain a documented data management process. In the process, address data sensitivity, data owner, handling of data, data retention limits, and disposal requirements, based on sensitivity and retention standards for the enterprise. Review and update documentation annually, or when significant enterprise changes occur that could impact this Safeguard.',\n  updated_at = NOW()\nWHERE id = 'c2373559-6e19-4d8d-9e34-cff91e6e25b1';

-- Update 3.3: Configure Data Access Control Lists...\nUPDATE requirements_library SET\n  title = 'Configure Data Access Control Lists',\n  description = 'Configure data access control lists based on a user''s need to know. Apply data access control lists, also known as access permissions, to local and remote file systems, databases, and applications.',\n  updated_at = NOW()\nWHERE id = 'faeceb77-afef-414b-8d95-b6509304b849';