-- Update 15.4: Ensure Service Provider Contracts Include Security Requireme...\nUPDATE requirements_library SET\n  title = 'Ensure Service Provider Contracts Include Security Requirements',\n  description = 'Ensure that service provider contracts include security requirements. Examples include notification for information security events, assessment and testing requirements, restrictions on personnel and service providers, intellectual property protection, and right to audit.',\n  updated_at = NOW()\nWHERE id = '6fcf52fd-52b0-40b2-80ad-480b93bacb9b';

-- Update 14.2: Train Workforce Members to Recognize Social Engineering Atta...\nUPDATE requirements_library SET\n  title = 'Train Workforce Members to Recognize Social Engineering Attacks',\n  description = 'Train workforce members to recognize social engineering attacks, such as phishing, pretexting, and tailgating.',\n  updated_at = NOW()\nWHERE id = 'b8c9515b-d71a-4f84-8912-b6a26bb6735e';

-- Update 15.5: Assess Service Providers...\nUPDATE requirements_library SET\n  title = 'Assess Service Providers',\n  description = 'Assess service providers consistent with the enterprise''s service provider policy. Assessment scope may vary based on classification from Safeguard 15.3, and may include review of standardized assessment reports, such as Service Organization Control 2 (SOC 2) Type 2 reports.',\n  updated_at = NOW()\nWHERE id = '64a3d801-1bd0-4367-913e-9a4f642e0772';

-- Update 15.6: Monitor Service Providers...\nUPDATE requirements_library SET\n  title = 'Monitor Service Providers',\n  description = 'Monitor service providers through log reviews, risk monitoring, or other mechanisms. Monitoring scope may vary based on classification from Safeguard 15.3.',\n  updated_at = NOW()\nWHERE id = '860ea81c-c33c-4d8c-9d05-21abdc9e49b1';

-- Update 8.11: Conduct Audit Log Reviews...\nUPDATE requirements_library SET\n  title = 'Conduct Audit Log Reviews',\n  description = 'Conduct reviews of audit logs to detect anomalies or abnormal events that could indicate a potential threat. Conduct reviews on a weekly basis.',\n  updated_at = NOW()\nWHERE id = '7e2c3876-570d-4d21-ad7e-73cd7a0b5332';

-- Update 8.1: Establish and Maintain an Audit Log Management Process...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain an Audit Log Management Process',\n  description = 'Establish and maintain an audit log management process that defines the enterprise''s logging requirements. At a minimum, address the collection, review, and retention of audit logs for enterprise assets. Review and update documentation annually, or when significant enterprise changes occur that could impact this Safeguard.',\n  updated_at = NOW()\nWHERE id = '097e3019-fe36-4998-927c-747aaae829f7';

-- Update 15.7: Securely Decommission Service Providers...\nUPDATE requirements_library SET\n  title = 'Securely Decommission Service Providers',\n  description = 'Securely decommission service providers by following a plan developed to meet the intended purpose. Examples include user access removal, enterprise asset removal, contract termination, and secure disposal of enterprise data.',\n  updated_at = NOW()\nWHERE id = 'a057c5a2-d604-4e6d-9cb8-65551db17dde';

-- Update 14.1: Establish and Maintain a Security Awareness Program...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Security Awareness Program',\n  description = 'Establish and maintain a security awareness program. The purpose of a security awareness program is to educate the enterprise''s workforce on how to interact with enterprise assets and data in a secure manner. Review and update documentation annually, or when significant enterprise changes occur that could impact this Safeguard.',\n  updated_at = NOW()\nWHERE id = '543ec2e3-adc9-41fe-8993-3f5d1d330c94';