-- Update 6.4: Require MFA for Remote Network Access...\nUPDATE requirements_library SET\n  title = 'Require MFA for Remote Network Access',\n  description = 'Require all users to use multi-factor authentication (MFA) for remote network access.',\n  updated_at = NOW()\nWHERE id = '837224bf-8953-41d9-80a5-3c8295096525';

-- Update 6.5: Require MFA for Administrative Access...\nUPDATE requirements_library SET\n  title = 'Require MFA for Administrative Access',\n  description = 'Require multi-factor authentication (MFA) for access to enterprise assets with administrative privileges.',\n  updated_at = NOW()\nWHERE id = 'fda453bb-4b2e-4581-b1ca-22503281bf83';

-- Update 6.8: Define and Maintain Role-Based Access Control...\nUPDATE requirements_library SET\n  title = 'Define and Maintain Role-Based Access Control',\n  description = 'Define and maintain role-based access control, through determining and documenting the access rights necessary for each role within the enterprise to successfully carry out their assigned duties. Perform access control reviews of enterprise assets to validate that all privileges are authorized, on a recurring schedule at a minimum annually, or more frequently.',\n  updated_at = NOW()\nWHERE id = 'b6263094-789a-4a72-bc90-b916d8cbeaab';

-- Update 7.7: Remediate Detected Vulnerabilities...\nUPDATE requirements_library SET\n  title = 'Remediate Detected Vulnerabilities',\n  description = 'Remediate detected vulnerabilities in software through processes and tooling on a monthly, or more frequent, basis, based on the remediation process.',\n  updated_at = NOW()\nWHERE id = '444150bb-e1d8-487f-95bc-e24eea2f5158';

-- Update 8.4: Standardize Time Synchronization...\nUPDATE requirements_library SET\n  title = 'Standardize Time Synchronization',\n  description = 'Standardize time synchronization. Configure networked and enterprise assets to implement network-based time sources. Time sources used by the enterprise shall be consistent with each other.',\n  updated_at = NOW()\nWHERE id = '87107031-69c2-4899-bb92-f4b3b2da676e';

-- Update 8.5: Collect Detailed Audit Logs...\nUPDATE requirements_library SET\n  title = 'Collect Detailed Audit Logs',\n  description = 'Configure detailed audit logging for enterprise assets containing sensitive data. Include event date, timestamp, source addresses, destination addresses, usernames, and process names associated with the event.',\n  updated_at = NOW()\nWHERE id = '2a7ebc21-79e3-43d8-b281-011529fe3246';

-- Update 8.6: Collect DNS Query Audit Logs...\nUPDATE requirements_library SET\n  title = 'Collect DNS Query Audit Logs',\n  description = 'Enable Domain Name System (DNS) query logging to collect DNS queries sent by enterprise assets.',\n  updated_at = NOW()\nWHERE id = 'e3786f03-e14e-485d-af1f-4828feb52546';

-- Update 7.2: Establish and Maintain a Remediation Process...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Remediation Process',\n  description = 'Establish and maintain a documented remediation process for enterprise assets with a vulnerability management process.',\n  updated_at = NOW()\nWHERE id = '1aa6eb13-d185-44f4-a7b0-7dd6c7637705';