-- Update 7.12: Cabling security...\nUPDATE requirements_library SET\n  title = 'Cabling security',\n  description = 'Cables carrying power, data or supporting information services shall be protected from interception, interference or damage.',\n  updated_at = NOW()\nWHERE id = '5ba6faf6-8cf4-484e-9769-61118c8ca5db';

-- Update 7.13: Equipment maintenance...\nUPDATE requirements_library SET\n  title = 'Equipment maintenance',\n  description = 'Equipment shall be maintained correctly to ensure availability, integrity and confidentiality of information.',\n  updated_at = NOW()\nWHERE id = '2792bff7-08b6-41e2-bd42-c5f9015aa4ea';

-- Update 7.14: Secure disposal or reuse of equipment...\nUPDATE requirements_library SET\n  title = 'Secure disposal or reuse of equipment',\n  description = 'Items of equipment containing storage media shall be verified to ensure that any sensitive data and licensed software has been removed or securely overwritten prior to disposal or reuse.',\n  updated_at = NOW()\nWHERE id = 'a8b012e5-6b12-4a15-b707-324f73af1993';

-- Update 8.8: Collect Command-Line Audit Logs...\nUPDATE requirements_library SET\n  title = 'Collect Command-Line Audit Logs',\n  description = 'Collect command-line audit logs. Example implementations include collecting audit logs from PowerShell®, BASH history, or Windows Command Prompt.',\n  updated_at = NOW()\nWHERE id = '25471430-573c-4cb2-959d-19f5ccf20c2c';

-- Update 8.7: Collect URL Request Audit Logs...\nUPDATE requirements_library SET\n  title = 'Collect URL Request Audit Logs',\n  description = 'Collect Uniform Resource Locator (URL) request logging. Logging systems need to be configured to collect URL requests from each of the enterprise''s web-facing applications.',\n  updated_at = NOW()\nWHERE id = '38a4133a-827c-4077-9339-6bbe23c047c5';

-- Update 8.13: Information backup...\nUPDATE requirements_library SET\n  title = 'Information backup',\n  description = 'Backup copies of information, software and systems shall be maintained and regularly tested in accordance with the agreed topic-specific policy on backup.',\n  updated_at = NOW()\nWHERE id = '4f07d106-8adf-4c35-862e-13f047df3cb0';

-- Update 8.14: Redundancy of information processing facilities...\nUPDATE requirements_library SET\n  title = 'Redundancy of information processing facilities',\n  description = 'Information processing facilities shall be implemented with redundancy sufficient to meet availability requirements.',\n  updated_at = NOW()\nWHERE id = '2a23e751-1a2c-4b06-ba2a-391dc41249b5';

-- Update 8.15: Logging...\nUPDATE requirements_library SET\n  title = 'Logging',\n  description = 'Logs that record activities, exceptions, faults and other relevant events shall be produced, stored, protected and analyzed.',\n  updated_at = NOW()\nWHERE id = 'ae1ed779-2701-475a-ba84-c4a44a0a6d73';