-- Update 17.4: Establish and Maintain an Incident Response Process...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain an Incident Response Process',\n  description = 'Establish and maintain an incident response process that addresses roles, responsibilities, and phases of incident response. Review annually, or when significant enterprise changes occur that could impact this Safeguard.',\n  updated_at = NOW()\nWHERE id = 'aa78133e-96ed-4406-afb3-2c3251f5b7b2';

-- Update 4.1: Establish and Maintain a Secure Configuration Process...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Secure Configuration Process',\n  description = 'Establish and maintain a documented secure configuration process for enterprise assets (end-user devices, including portable and mobile, non-computing/IoT devices, and servers) and software (operating systems and applications). Review and update documentation annually, or when significant enterprise changes occur that could impact this Safeguard.',\n  updated_at = NOW()\nWHERE id = '1c097266-6870-441d-81f5-2f691d960ab8';

-- Update 4.2: Establish and Maintain a Secure Configuration Process for Ne...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Secure Configuration Process for Network Infrastructure',\n  description = 'Establish and maintain a documented secure configuration process for network infrastructure. Review and update documentation annually, or when significant enterprise changes occur that could impact this Safeguard.',\n  updated_at = NOW()\nWHERE id = '0a425658-45ca-4354-9006-79c34fa9590d';

-- Update 5.4: Restrict Administrator Privileges to Dedicated Administrator...\nUPDATE requirements_library SET\n  title = 'Restrict Administrator Privileges to Dedicated Administrator Accounts',\n  description = 'Restrict administrator privileges to dedicated administrator accounts on enterprise assets. Conduct general computing activities, such as internet browsing, email, and productivity suite use, from the user''s standard account.',\n  updated_at = NOW()\nWHERE id = '21140b65-83bb-4e85-a385-73fe6272e34b';

-- Update 6.1: Establish an Access Granting Process...\nUPDATE requirements_library SET\n  title = 'Establish an Access Granting Process',\n  description = 'Establish and follow a process for granting access to enterprise assets upon new hire, promotion, or role change of a user.',\n  updated_at = NOW()\nWHERE id = '0016b577-f633-4325-9da4-8c877bf799f1';

-- Update 17.5: Assign Key Roles and Responsibilities...\nUPDATE requirements_library SET\n  title = 'Assign Key Roles and Responsibilities',\n  description = 'Assign key roles and responsibilities for incident response, including staff from legal, IT, information security, facilities, public relations, human resources, incident analysts, and investigators. Review annually, or when significant enterprise changes occur that could impact this Safeguard.',\n  updated_at = NOW()\nWHERE id = 'd7c1dde7-fafb-4281-b1ea-7c460c01c674';

-- Update 17.7: Conduct Routine Incident Response Exercises...\nUPDATE requirements_library SET\n  title = 'Conduct Routine Incident Response Exercises',\n  description = 'Plan and conduct routine incident response exercises and scenarios for key personnel, including elements of communication, coordination, decision making, and workflow.',\n  updated_at = NOW()\nWHERE id = '1b839d74-a0f6-4d09-84e1-ae06b18e0581';

-- Update 17.9: Establish and Maintain Security Incident Thresholds...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain Security Incident Thresholds',\n  description = 'Establish and maintain security incident thresholds, including at a minimum, differentiating between incident types that require escalation and those that do not.',\n  updated_at = NOW()\nWHERE id = '77525d37-7f50-455d-a637-ee3a78cd3964';