-- Update 18.4: Validate Security Measures...\nUPDATE requirements_library SET\n  title = 'Validate Security Measures',\n  description = 'Validate security measures by conducting simulated cyber attacks, by using threat hunting techniques, and by instituting a bug bounty program, or a combination thereof.',\n  updated_at = NOW()\nWHERE id = '94e98ca5-dc6c-418c-a578-4c417d2bcf3b';

-- Update 18.3: Remedy Penetration Test Findings...\nUPDATE requirements_library SET\n  title = 'Remedy Penetration Test Findings',\n  description = 'Remediate penetration test findings based on the enterprise''s policy for remediation scope and prioritization.',\n  updated_at = NOW()\nWHERE id = 'cc0a7899-09bc-444f-9e15-7de1dafaac13';

-- Update 13.6: Collect Network Traffic Flow Logs...\nUPDATE requirements_library SET\n  title = 'Collect Network Traffic Flow Logs',\n  description = 'Collect network traffic flow logs and/or network traffic to review and alert upon. Logs useful for incident response are NetFlow, SFlow, and IPFIX.',\n  updated_at = NOW()\nWHERE id = '04389565-789f-46f8-b591-e683898bf430';

-- Update 14.6: Train Workforce Members on Recognizing and Reporting Securit...\nUPDATE requirements_library SET\n  title = 'Train Workforce Members on Recognizing and Reporting Security Incidents',\n  description = 'Train workforce members to be able to recognize a potential incident and be able to report such an incident.',\n  updated_at = NOW()\nWHERE id = '0dea022d-ba54-4b9d-9e95-c49269163256';

-- Update 18.5: Perform Periodic Internal Penetration Tests...\nUPDATE requirements_library SET\n  title = 'Perform Periodic Internal Penetration Tests',\n  description = 'Perform periodic internal penetration tests based on program requirements, no less than annually.',\n  updated_at = NOW()\nWHERE id = '604a8e02-68a8-4e50-ab5d-18025cd9576a';

-- Update 13.10: Perform Application Layer Filtering...\nUPDATE requirements_library SET\n  title = 'Perform Application Layer Filtering',\n  description = 'Perform application layer filtering for email. Example implementations include spam filtering, phishing filtering, attachment blocking, and link blocking.',\n  updated_at = NOW()\nWHERE id = 'c189d8c6-8649-4881-bc81-40ee9d778718';

-- Update 15.1: Establish and Maintain an Inventory of Service Providers...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain an Inventory of Service Providers',\n  description = 'Establish and maintain an inventory of service providers. Implementation: Maintain comprehensive inventory of all service providers and vendors. Document service provider relationships and dependencies. Classify service providers based on risk and criticality. Regular review and validation of service provider inventory.',\n  updated_at = NOW()\nWHERE id = 'a5bd30a4-3a0d-474f-8200-30998fcd7223';

-- Update 16.13: Conduct Application Penetration Testing...\nUPDATE requirements_library SET\n  title = 'Conduct Application Penetration Testing',\n  description = 'Conduct application penetration testing. For critical web applications, conduct penetration testing annually, at minimum.',\n  updated_at = NOW()\nWHERE id = '2e37bae6-4634-47bc-a0aa-3070792dd5c0';