-- Update 5.3: Disable Dormant Accounts...\nUPDATE requirements_library SET\n  title = 'Disable Dormant Accounts',\n  description = 'Delete or disable any dormant accounts after a period of 45 days of inactivity, where supported.',\n  updated_at = NOW()\nWHERE id = '178edab1-3116-4926-b77d-de9cb82eb710';

-- Update 8.9: Centralize Audit Logs...\nUPDATE requirements_library SET\n  title = 'Centralize Audit Logs',\n  description = 'Centralize, to the extent possible, audit log collection and retention across enterprise assets.',\n  updated_at = NOW()\nWHERE id = '9175d6e0-fda8-469f-a579-4a985e96b31a';

-- Update 11.3: Protect Recovery Data...\nUPDATE requirements_library SET\n  title = 'Protect Recovery Data',\n  description = 'Protect recovery data with equivalent controls to the original data. Reference encryption or data separation examples include encryption or air-gapped systems.',\n  updated_at = NOW()\nWHERE id = '6bc57182-629b-43ab-8869-baca01f8bd56';

-- Update 12.8: Establish and Maintain Dedicated Computing Resources for All...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain Dedicated Computing Resources for All Administrative Work',\n  description = 'Establish and maintain dedicated computing resources, on separated VLANs or in cloud environments, for all enterprise administrative tasks. Example implementations include administrative Virtual Machines (VMs) on workstations or domain administrative accounts.',\n  updated_at = NOW()\nWHERE id = 'c5e017dd-9cfe-45b0-b70b-a3d3831d429b';

-- Update 13.2: Deploy a Host-Based Intrusion Detection System...\nUPDATE requirements_library SET\n  title = 'Deploy a Host-Based Intrusion Detection System',\n  description = 'Deploy a Host-based Intrusion Detection System (HIDS) solution on enterprise assets, where appropriate and/or necessary.',\n  updated_at = NOW()\nWHERE id = '30ba3c02-7f4b-4852-bbd9-e67d10872e84';

-- Update 13.1: Centralize Security Event Alerting...\nUPDATE requirements_library SET\n  title = 'Centralize Security Event Alerting',\n  description = 'Centralize security event alerting across enterprise assets for log correlation and analysis. Best practice implementation requires the use of a Security Information and Event Management (SIEM) system.',\n  updated_at = NOW()\nWHERE id = '8081716a-5fcc-4a8e-be8d-2b47e3078a0e';

-- Update 5.1: Establish and Maintain an Inventory of Accounts...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain an Inventory of Accounts',\n  description = 'Establish and maintain an inventory of all accounts managed in the enterprise. The inventory shall include both user and administrator accounts. The inventory shall include the person or entity the account belongs to, the systems it applies to, and an active or inactive status. Review the inventory quarterly, or more frequently.',\n  updated_at = NOW()\nWHERE id = 'a44b8a8a-fc17-4e7f-93d1-fbcef0b07a81';

-- Update 2.6: Allowlist Authorized Software Libraries...\nUPDATE requirements_library SET\n  title = 'Allowlist Authorized Software Libraries',\n  description = 'Allowlist authorized software libraries, such as specific .dll, .ocx, .so files, which are allowed to be loaded by authorized software. Implementation: Identify and catalog authorized software libraries. Implement library allowlisting controls. Monitor library loading activities. Maintain approved library versions.',\n  updated_at = NOW()\nWHERE id = 'ea41fd40-3a25-465e-b8fc-96af7ddc7b96';