-- Update 7.2: Establish and Maintain a Remediation Process...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Remediation Process',\n  description = 'Establish and maintain a documented remediation process for enterprise assets with a vulnerability management process.',\n  updated_at = NOW()\nWHERE id = '51b9c5f4-af70-4df0-b0f3-e37c201aaef4';

-- Update 7.3: Perform Automated Operating System Patch Management...\nUPDATE requirements_library SET\n  title = 'Perform Automated Operating System Patch Management',\n  description = 'Perform operating system updates on enterprise assets through automated patch management on a monthly, or more frequent, basis.',\n  updated_at = NOW()\nWHERE id = 'dc56b944-1f5b-41aa-8228-5fae9fda1b91';

-- Update 8.1: Establish and Maintain an Audit Log Management Process...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain an Audit Log Management Process',\n  description = 'Establish and maintain an audit log management process that defines the enterprise''s logging requirements. At a minimum, address the collection, review, and retention of audit logs for enterprise assets. Review and update documentation annually, or when significant enterprise changes occur that could impact this Safeguard.',\n  updated_at = NOW()\nWHERE id = '7e31c3ee-852e-4be0-8a65-e769307226bf';

-- Update 8.3: Ensure Adequate Audit Log Storage...\nUPDATE requirements_library SET\n  title = 'Ensure Adequate Audit Log Storage',\n  description = 'Ensure that logging destinations maintain adequate storage to comply with the enterprise''s audit log management process.',\n  updated_at = NOW()\nWHERE id = '92ef5de6-83c7-436f-8b10-89e587f67306';

-- Update 9.1: Ensure Use of Only Fully Supported Browsers and Email Client...\nUPDATE requirements_library SET\n  title = 'Ensure Use of Only Fully Supported Browsers and Email Clients',\n  description = 'Ensure only fully supported browsers and email clients are allowed to execute in the enterprise, only using the latest version of browsers and email clients provided by the vendor.',\n  updated_at = NOW()\nWHERE id = 'acbabd18-4c99-471c-b0f2-07270f54cce8';

-- Update 8.2: Collect Audit Logs...\nUPDATE requirements_library SET\n  title = 'Collect Audit Logs',\n  description = 'Collect audit logs from enterprise assets with a logging configuration in accordance with the audit log management process.',\n  updated_at = NOW()\nWHERE id = 'e7432c41-70ac-44f2-ad03-db7a5b745ea3';

-- Update 4.4: Implement and Manage a Firewall on Servers...\nUPDATE requirements_library SET\n  title = 'Implement and Manage a Firewall on Servers',\n  description = 'Implement and manage a firewall on servers, where supported. Example implementations include a virtual firewall, operating system firewall, or a physical firewall.',\n  updated_at = NOW()\nWHERE id = '5a3e0f4f-55ff-4bc3-97b2-802acdb032e6';

-- Update 7.5: Perform Automated Vulnerability Scans of Internal Enterprise...\nUPDATE requirements_library SET\n  title = 'Perform Automated Vulnerability Scans of Internal Enterprise Assets',\n  description = 'Perform automated vulnerability scans of internal enterprise assets on a quarterly, or more frequent, basis. Conduct such scans from multiple vantage points.',\n  updated_at = NOW()\nWHERE id = 'f0cffc32-f3c7-4427-a75f-b487f22fb321';