-- Update 5.13: Labelling of information...\nUPDATE requirements_library SET\n  title = 'Labelling of information',\n  description = 'An appropriate set of procedures for information labelling shall be developed and implemented in accordance with the information classification scheme adopted by the organization.',\n  updated_at = NOW()\nWHERE id = '3f2e6e97-8e31-4b9e-b089-43c48404987a';

-- Update 5.14: Information transfer...\nUPDATE requirements_library SET\n  title = 'Information transfer',\n  description = 'Information transfer rules, procedures, or agreements shall be in place for all types of transfer facilities within the organization and between the organization and other parties.',\n  updated_at = NOW()\nWHERE id = 'bb142b0d-1505-4a69-83c6-743fdfa02d35';

-- Update 5.15: Access control...\nUPDATE requirements_library SET\n  title = 'Access control',\n  description = 'Rules to control physical and logical access to information and other associated assets shall be established and implemented based on business and information security requirements.',\n  updated_at = NOW()\nWHERE id = '600b22e9-725e-41fd-b8b6-4e6bcf2102ea';

-- Update 5.16: Identity management...\nUPDATE requirements_library SET\n  title = 'Identity management',\n  description = 'The full life cycle of identities shall be managed.',\n  updated_at = NOW()\nWHERE id = '38ebd2d4-cec7-49be-b07c-2fa541ac468b';

-- Update 5.17: Authentication information...\nUPDATE requirements_library SET\n  title = 'Authentication information',\n  description = 'Allocation and management of authentication information shall be controlled by a management process, including advising personnel on appropriate handling of authentication information.',\n  updated_at = NOW()\nWHERE id = '4cd3c62b-20f8-4cd9-aea8-a4eddd1db3df';

-- Update 5.18: Access rights...\nUPDATE requirements_library SET\n  title = 'Access rights',\n  description = 'Access rights to information and other associated assets shall be provisioned, reviewed, modified and removed in accordance with the organization''s topic-specific policy on access control.',\n  updated_at = NOW()\nWHERE id = '0a4df158-492f-464b-b259-80518454f1c8';

-- Update 5.19: Information security in supplier relationships...\nUPDATE requirements_library SET\n  title = 'Information security in supplier relationships',\n  description = 'Processes and procedures shall be defined and implemented to manage the information security risks associated with the use of supplier''s products or services.',\n  updated_at = NOW()\nWHERE id = '2bf86e27-482b-4bd0-bf46-17172e24ea54';

-- Update 5.20: Addressing information security within supplier agreements...\nUPDATE requirements_library SET\n  title = 'Addressing information security within supplier agreements',\n  description = 'Relevant information security requirements shall be established and agreed with each supplier that can access, process, store, communicate, or provide IT infrastructure components for, the organization''s information.',\n  updated_at = NOW()\nWHERE id = '3cf74379-9350-4821-ad91-31c0a5a91f9c';