-- Update 16.7: Use Standard Hardening Configuration Templates for Applicati...\nUPDATE requirements_library SET\n  title = 'Use Standard Hardening Configuration Templates for Application Infrastructure',\n  description = 'Use standard, industry-recommended hardening configuration templates for application infrastructure components. This includes underlying servers, databases, and web servers, and applies to cloud containers, Platform as a Service (PaaS) components, or Software as a Service (SaaS) components used as application infrastructure.',\n  updated_at = NOW()\nWHERE id = 'a6ff9f49-a96f-40e2-ae21-69d9fe64042b';

-- Update 8.2: Collect Audit Logs...\nUPDATE requirements_library SET\n  title = 'Collect Audit Logs',\n  description = 'Collect audit logs from enterprise assets with a logging configuration in accordance with the audit log management process.',\n  updated_at = NOW()\nWHERE id = 'fc69876a-9d8c-4d83-b52f-2e091fe2116d';

-- Update 7.6: Perform Automated Vulnerability Scans of Externally-Exposed ...\nUPDATE requirements_library SET\n  title = 'Perform Automated Vulnerability Scans of Externally-Exposed Enterprise Assets',\n  description = 'Perform automated vulnerability scans of externally-exposed enterprise assets using either an internal or external scanning utility. Perform scans on a monthly, or more frequent, basis.',\n  updated_at = NOW()\nWHERE id = '31a1bd24-f325-4fa6-86d7-e9ffb26609ee';

-- Update 7.7: Remediate Detected Vulnerabilities...\nUPDATE requirements_library SET\n  title = 'Remediate Detected Vulnerabilities',\n  description = 'Remediate detected vulnerabilities in software through processes and tooling on a monthly, or more frequent, basis, based on the remediation process.',\n  updated_at = NOW()\nWHERE id = 'bac15c8e-3535-451e-8798-db2c05426564';

-- Update 7.3: Perform Automated Operating System Patch Management...\nUPDATE requirements_library SET\n  title = 'Perform Automated Operating System Patch Management',\n  description = 'Perform operating system updates on enterprise assets through automated patch management on a monthly, or more frequent, basis.',\n  updated_at = NOW()\nWHERE id = '6befd75b-f60d-4916-a4ca-792e140a73e5';

-- Update 8.4: Standardize Time Synchronization...\nUPDATE requirements_library SET\n  title = 'Standardize Time Synchronization',\n  description = 'Standardize time synchronization. Configure networked and enterprise assets to implement network-based time sources. Time sources used by the enterprise shall be consistent with each other.',\n  updated_at = NOW()\nWHERE id = '57194bab-d46c-46eb-aea2-8ef71fa2e860';

-- Update 8.5: Collect Detailed Audit Logs...\nUPDATE requirements_library SET\n  title = 'Collect Detailed Audit Logs',\n  description = 'Configure detailed audit logging for enterprise assets containing sensitive data. Include event date, timestamp, source addresses, destination addresses, usernames, and process names associated with the event.',\n  updated_at = NOW()\nWHERE id = 'f28d19e8-558b-45a0-ac21-a094596050cd';

-- Update 3.1: Establish and Maintain a Data Management Process...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Data Management Process',\n  description = 'Establish and maintain a documented data management process. In the process, address data sensitivity, data owner, handling of data, data retention limits, and disposal requirements, based on sensitivity and retention standards for the enterprise. Review and update documentation annually, or when significant enterprise changes occur that could impact this Safeguard.',\n  updated_at = NOW()\nWHERE id = 'e578cd72-65e1-4381-9136-cc0b67b941f5';