-- Update 16.11: Leverage Vetted Modules or Services for Application Security...\nUPDATE requirements_library SET\n  title = 'Leverage Vetted Modules or Services for Application Security Components',\n  description = 'Leverage vetted modules or services for application security components, such as identity management, encryption, and auditing, instead of creating custom code for these features. Use only standardized, currently maintained, and extensively reviewed encryption algorithms.',\n  updated_at = NOW()\nWHERE id = 'a197e631-0516-43b1-88db-ce44ecc582b2';

-- Update 4.11: Enforce Remote Wipe Capability on Portable End-User Devices...\nUPDATE requirements_library SET\n  title = 'Enforce Remote Wipe Capability on Portable End-User Devices',\n  description = 'Remotely wipe enterprise data from portable end-user devices when deemed appropriate. Enterprise devices storing sensitive data, where supported, shall have remote wipe capabilities.',\n  updated_at = NOW()\nWHERE id = 'ade37a10-3ef3-41db-85d2-caad149b494a';

-- Update 4.12: Separate Enterprise Workspaces on Mobile End-User Devices...\nUPDATE requirements_library SET\n  title = 'Separate Enterprise Workspaces on Mobile End-User Devices',\n  description = 'Ensure separate enterprise workspaces are used on mobile end-user devices, where supported. Example implementations include using an Apple® Configuration Profile or Android™ Work Profile to separate enterprise applications and data from personal applications and data.',\n  updated_at = NOW()\nWHERE id = '70b03ab6-1c16-4b0d-af33-b9b4ff1fe8cc';

-- Update 17.2: Establish and Maintain Contact Information for Reporting Sec...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain Contact Information for Reporting Security Incidents',\n  description = 'Establish and maintain contact information for reporting security incidents. Implementation: Maintain current contact information for incident reporting. Establish multiple communication channels for incident notification. Provide clear guidance on when and how to report incidents. Ensure contact information is readily accessible to all personnel.',\n  updated_at = NOW()\nWHERE id = '807b499c-ee8e-40ce-9b22-8f529822d491';

-- Update 17.3: Establish and Maintain an Enterprise Process for Reporting I...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain an Enterprise Process for Reporting Incidents',\n  description = 'Establish and maintain an enterprise process for reporting incidents. Implementation: Develop comprehensive incident reporting procedures. Define incident classification and severity levels. Establish reporting timelines and escalation procedures. Train all personnel on incident reporting requirements.',\n  updated_at = NOW()\nWHERE id = 'c95cd2a5-b52b-4e93-8e31-ecfb421e4136';

-- Update 7.5: Perform Automated Vulnerability Scans of Internal Enterprise...\nUPDATE requirements_library SET\n  title = 'Perform Automated Vulnerability Scans of Internal Enterprise Assets',\n  description = 'Perform automated vulnerability scans of internal enterprise assets on a quarterly, or more frequent, basis. Conduct such scans from multiple vantage points.',\n  updated_at = NOW()\nWHERE id = '37538586-21c1-49a6-ac1e-5be31eb7ce35';

-- Update 4.4: Implement and Manage a Firewall on Servers...\nUPDATE requirements_library SET\n  title = 'Implement and Manage a Firewall on Servers',\n  description = 'Implement and manage a firewall on servers, where supported. Example implementations include a virtual firewall, operating system firewall, or a physical firewall.',\n  updated_at = NOW()\nWHERE id = '49c15807-872e-4544-a777-9d16e801099a';

-- Update 17.6: Define Mechanisms for Communicating During Incident Response...\nUPDATE requirements_library SET\n  title = 'Define Mechanisms for Communicating During Incident Response',\n  description = 'Define mechanisms for communicating during incident response. Mechanisms may include phone calls, emails, or letters. Ensure that contact information is up-to-date and that personnel know how to use communication mechanisms securely.',\n  updated_at = NOW()\nWHERE id = '9431005e-b7cb-4c80-953e-5ebea26d422e';