-- Update 4.7: Manage Default Accounts on Enterprise Assets and Software...\nUPDATE requirements_library SET\n  title = 'Manage Default Accounts on Enterprise Assets and Software',\n  description = 'Manage default accounts on enterprise assets and software, such as root, administrator, and other pre-configured vendor accounts. Example implementations can include: disabling default accounts or making them unusable.',\n  updated_at = NOW()\nWHERE id = 'afcbcfa3-9f3a-40a4-946e-b1390647218b';

-- Update 12.2: Establish and Maintain a Secure Network Architecture...\nUPDATE requirements_library SET\n  title = 'Establish and Maintain a Secure Network Architecture',\n  description = 'Establish and maintain a secure network architecture. A secure network architecture must address segmentation, least privilege, and availability, at a minimum.',\n  updated_at = NOW()\nWHERE id = 'e7478282-3cd4-4a3c-b60c-6e88e28f804a';

-- Update 10.2: Configure Automatic Anti-Malware Signature Updates...\nUPDATE requirements_library SET\n  title = 'Configure Automatic Anti-Malware Signature Updates',\n  description = 'Configure automatic anti-malware signature updates on all enterprise assets.',\n  updated_at = NOW()\nWHERE id = 'fb1a822a-38d8-4379-b6a3-7a522963a55b';

-- Update 10.3: Disable Autorun and Autoplay for Removable Media...\nUPDATE requirements_library SET\n  title = 'Disable Autorun and Autoplay for Removable Media',\n  description = 'Disable autorun and autoplay auto-execute functionality for removable media.',\n  updated_at = NOW()\nWHERE id = '6753390e-ddb0-41c6-8550-8247f1dbfb4e';

-- Update 10.1: Deploy and Maintain Anti-Malware Software...\nUPDATE requirements_library SET\n  title = 'Deploy and Maintain Anti-Malware Software',\n  description = 'Deploy and maintain anti-malware software on all enterprise assets.',\n  updated_at = NOW()\nWHERE id = 'b50473e9-903a-4313-9487-3e89780d3b98';

-- Update 10.5: Enable Anti-Exploitation Features...\nUPDATE requirements_library SET\n  title = 'Enable Anti-Exploitation Features',\n  description = 'Enable anti-exploitation features on enterprise assets and software, where possible, such as Microsoft® Data Execution Prevention (DEP), Windows® Defender Exploit Guard (WDEG), or Apple® System Integrity Protection (SIP) and Gatekeeper™.',\n  updated_at = NOW()\nWHERE id = 'ac591902-bb65-4a6c-a5e1-28b64b8a4896';

-- Update 10.6: Centrally Manage Anti-Malware Software...\nUPDATE requirements_library SET\n  title = 'Centrally Manage Anti-Malware Software',\n  description = 'Use a centrally managed anti-malware software to continuously monitor and defend each of the enterprise''s workstations and servers.',\n  updated_at = NOW()\nWHERE id = 'f42e8983-fbd7-4c21-aa54-35c51af27e1b';

-- Update 9.7: Deploy and Maintain Email Server Anti-Malware Protections...\nUPDATE requirements_library SET\n  title = 'Deploy and Maintain Email Server Anti-Malware Protections',\n  description = 'Deploy and maintain email server anti-malware protections, such as attachment scanning and/or sandboxing.',\n  updated_at = NOW()\nWHERE id = '056f2975-a696-4994-9cfd-5d3937b095b5';