apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: audit-readiness-hub-production

namespace: audit-readiness-hub-prod

namePrefix: prod-

resources:
- ../../base

patchesStrategicMerge:
- deployment-patch.yaml
- ingress-patch.yaml
- hpa-patch.yaml

configMapGenerator:
- name: audit-readiness-hub-config
  behavior: merge
  literals:
  - NODE_ENV=production
  - VITE_APP_ENV=production
  - ENABLE_DEBUG_LOGS=false
  - ENABLE_MONITORING=true
  - ENABLE_SECURITY_HEADERS=true
  - CACHE_TTL_DEFAULT=600
  - CACHE_TTL_DASHBOARD=300
  - CACHE_TTL_STATIC=3600

images:
- name: audit-readiness-hub
  newName: audit-readiness-hub
  newTag: v1.0.0

commonLabels:
  environment: production
  tier: frontend

commonAnnotations:
  environment: production
  deployment.kubernetes.io/revision: "1"

replicas:
- name: audit-readiness-hub
  count: 5