name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: true # Important for the deployment action
          fetch-depth: 0 # Fetch all history for accurate access to repository files

      - name: Verify package-lock.json
        run: |
          ls -la
          if [ -f "package-lock.json" ]; then
            echo "package-lock.json exists"
          else
            echo "package-lock.json does not exist"
            exit 1
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # The folder the action should deploy
          branch: main # Deploy to the main branch root
          target-folder: docs # GitHub Pages can serve from /docs folder in main branch
          token: ${{ secrets.GITHUB_TOKEN }} # Using the built-in token 