# This workflow has been disabled to prevent branch divergence issues
# It was overwriting source code with built files, causing deployment problems
# Vercel handles deployment directly from source code now

name: "Disabled Workflow"
on:
  workflow_dispatch:
    
jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Disabled
        run: echo "This workflow has been disabled to prevent branch divergence" 